# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('parts_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'amoeba__Product_Parts',
            },
        ),
        migrations.CreateModel(
            name='Product_Parts_Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_name', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'amoeba__Product_Parts_Kit',
            },
        ),
        migrations.CreateModel(
            name='Product_Parts_Kit_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'amoeba__Product_Parts_Kit_Items',
            },
        ),
        migrations.CreateModel(
            name='Profile_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.CharField(blank=True, max_length=225, null=True)),
                ('weight_per_lm', models.CharField(blank=True, max_length=255, null=True)),
                ('formula', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'amoeba__Profile_items',
            },
        ),
        migrations.CreateModel(
            name='Profile_Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(blank=True, max_length=225, null=True)),
                ('kit_weight_lm', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True)),
                ('parts_kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_items_kit', to='product_parts.product_parts_kit')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parts_kit', to='product_master.product')),
            ],
            options={
                'db_table': 'amoeba__Profile_Kit',
            },
        ),
    ]
