# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('product_parts', '0001_initial'),
        ('product_master', '0001_initial'),
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_kit',
            name='profile_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_kit_series', to='profiles.profilemasterseries'),
        ),
        migrations.AddField(
            model_name='profile_kit',
            name='profile_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_kit_type', to='profiles.profilemastertype'),
        ),
        migrations.AddField(
            model_name='profile_kit',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_system', to='brands.categorybrands'),
        ),
        migrations.AddField(
            model_name='profile_items',
            name='parts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_part', to='product_parts.product_parts_kit_items'),
        ),
        migrations.AddField(
            model_name='profile_items',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_item', to='profiles.profiles'),
        ),
        migrations.AddField(
            model_name='profile_items',
            name='profile_kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_items_kit', to='product_parts.profile_kit'),
        ),
        migrations.AddField(
            model_name='product_parts_kit_items',
            name='parts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_kit_parts', to='product_parts.parts'),
        ),
        migrations.AddField(
            model_name='product_parts_kit_items',
            name='product_parts_kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_kit_item', to='product_parts.product_parts_kit'),
        ),
        migrations.AddField(
            model_name='product_parts_kit',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_parts_kit', to='product_master.product'),
        ),
    ]
