# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categories', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_parts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parts_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parts',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parts',
            name='parts_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parts_category', to='Categories.category'),
        ),
    ]
