# Generated by Django 3.2.4 on 2025-04-20 07:27

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('enquiry_category', models.IntegerField(blank=True, choices=[(1, 'Client'), (2, 'In House')], null=True)),
                ('enquiry_id', models.CharField(blank=True, max_length=25, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notifications', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'Estimating'), (4, 'Inactive'), (5, 'Management Approved'), (6, 'Lose'), (7, 'Enquiry On Hold'), (8, 'Awarded'), (9, 'Management Review'), (10, 'Quotation Sent'), (0, 'Test')], default=1, null=True)),
                ('labour_percentage', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('overhead_percentage', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('pricing_type_select', models.IntegerField(blank=True, choices=[(1, 'International'), (2, 'Local')], null=True)),
                ('price_per_kg', models.CharField(blank=True, max_length=10, null=True)),
                ('price_per_kg_markup', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('enquiry_active_status', models.BooleanField(blank=True, default=True, null=True)),
                ('structural_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weather_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('enquiry_type', models.IntegerField(blank=True, choices=[(1, 'Ongoing'), (2, 'Tender')], null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('active_hrs', models.DurationField(default=datetime.timedelta(0))),
                ('other_notes', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'amoeba__Enquiries',
            },
        ),
        migrations.CreateModel(
            name='Enquiry_Discontinued_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('discontinue_note', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'amoeba__Enquiry_Discontinued_History',
            },
        ),
        migrations.CreateModel(
            name='Enquiry_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.CharField(blank=True, max_length=225, null=True)),
                ('action', models.IntegerField(blank=True, choices=[(1, 'Create'), (2, 'Update'), (3, 'Delete'), (4, 'Export'), (5, 'Download')], null=True)),
            ],
            options={
                'db_table': 'amoeba__Enquiry_Log',
            },
        ),
        migrations.CreateModel(
            name='EnquirySpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('identifier', models.CharField(blank=True, max_length=50, null=True)),
                ('is_description', models.BooleanField(default=False)),
                ('specification_description', models.CharField(blank=True, max_length=225, null=True)),
                ('specification_type', models.IntegerField(choices=[(1, 'predefined'), (2, 'Custom')], default=1)),
                ('minimum_price', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
            ],
            options={
                'db_table': 'amoeba__EnquirySpecifications',
            },
        ),
        migrations.CreateModel(
            name='EnquiryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_time', models.DurationField(default=datetime.timedelta(0))),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.CharField(default='00:00:00', max_length=8)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Active'), (2, 'In Progress'), (3, 'Management Review'), (4, 'Re-Estimating'), (5, 'Quotation On Hold'), (6, 'Approved'), (7, 'Inactive'), (9, 'Estimating'), (10, 'Quote'), (12, 'Quotation Sent'), (13, 'Customer Approved'), (14, 'Recalled'), (15, 'Approved with Signature')], null=True)),
            ],
            options={
                'db_table': 'amoeba__EnquiryUsers',
            },
        ),
        migrations.CreateModel(
            name='EstimationNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('management', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.BooleanField(blank=True, default=False, null=True)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('note_status', models.IntegerField(blank=True, choices=[(1, 'Yet to Start'), (2, 'Active'), (3, 'Submitted'), (4, 'Re-Estimating'), (5, 'Quotation On Hold'), (6, 'Managment Approved'), (7, 'Discontinued'), (8, 'Reopened'), (9, 'Estimating'), (10, 'Quote'), (12, 'Quotation Sent'), (13, 'Recalled'), (14, 'Customer Approved'), (15, 'Approved with Signature')], null=True)),
                ('is_replay', models.BooleanField(blank=True, default=False, null=True)),
                ('note_readed', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'amoeba__Estimation_Notes',
            },
        ),
        migrations.CreateModel(
            name='Estimations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'amoeba__Estimations',
            },
        ),
        migrations.CreateModel(
            name='Pricing_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_of_work', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True)),
                ('product_summary', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True)),
                ('weightage_summary', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True)),
                ('material_summary', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True)),
                ('pricing_review_summary', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True)),
                ('quotation', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True)),
            ],
            options={
                'db_table': 'amoeba__Pricing_Summary',
            },
        ),
        migrations.CreateModel(
            name='Temp_EnquirySpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('identifier', models.CharField(blank=True, max_length=50, null=True)),
                ('is_description', models.BooleanField(default=False)),
                ('specification_description', models.CharField(blank=True, max_length=225, null=True)),
                ('specification_type', models.IntegerField(choices=[(1, 'predefined'), (2, 'Custom')], default=1)),
                ('minimum_price', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
            ],
            options={
                'db_table': 'amoeba__Temp_EnquirySpecifications',
            },
        ),
        migrations.CreateModel(
            name='Temp_EstimationNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('management', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.BooleanField(blank=True, default=False, null=True)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('note_status', models.IntegerField(blank=True, choices=[(1, 'Yet to Start'), (2, 'Active'), (3, 'Submitted'), (4, 'Re-Estimating'), (5, 'On Hold'), (6, 'Managment Approved'), (7, 'Discontinued'), (8, 'Reopened'), (9, 'Estimating'), (10, 'Quote'), (12, 'Quotation Sent'), (13, 'Recalled'), (14, 'Customer Approved'), (15, 'Approved with Signature')], null=True)),
                ('is_replay', models.BooleanField(blank=True, default=False, null=True)),
                ('note_readed', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'amoeba__Temp_Estimation_Notes',
            },
        ),
        migrations.CreateModel(
            name='Temp_Estimations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'amoeba__Temp_Estimations',
            },
        ),
        migrations.CreateModel(
            name='Temp_Pricing_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_of_work', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True)),
                ('product_summary', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True)),
                ('weightage_summary', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True)),
                ('material_summary', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True)),
                ('pricing_review_summary', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True)),
                ('quotation', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True)),
                ('estimation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_pricing_summary_estimation', to='enquiries.temp_estimations')),
            ],
            options={
                'db_table': 'amoeba__Temp_Pricing_Summary',
            },
        ),
    ]
