# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_master', '0001_initial'),
        ('product_parts', '0002_initial'),
        ('industry_type', '0001_initial'),
        ('panels_and_others', '0001_initial'),
        ('brands', '0002_initial'),
        ('customers', '0002_initial'),
        ('companies', '0002_companies_last_modified_by'),
        ('enquiries', '0001_initial'),
        ('Categories', '0002_initial'),
        ('estimations', '0001_initial'),
        ('profiles', '0001_initial'),
        ('pricing_master', '0002_surface_finish_kit_surface_finish'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_estimations',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_estimation_tab_temp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_estimations',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimation_enquiry_temp', to='enquiries.enquiries'),
        ),
        migrations.AddField(
            model_name='temp_estimations',
            name='inherited_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimation_inherited_revision_temp', to='estimations.estimationversions'),
        ),
        migrations.AddField(
            model_name='temp_estimations',
            name='inherited_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimation_inherited_version_temp', to='estimations.estimationmaniversion'),
        ),
        migrations.AddField(
            model_name='temp_estimations',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_estimations',
            name='parent_estimation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_estimation_on_temp', to='enquiries.estimations'),
        ),
        migrations.AddField(
            model_name='temp_estimations',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimation_version_temp', to='estimations.estimationversions'),
        ),
        migrations.AddField(
            model_name='temp_estimationnotes',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_estimation_notes_temp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_estimationnotes',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_enquiry_temp', to='enquiries.enquiries'),
        ),
        migrations.AddField(
            model_name='temp_estimationnotes',
            name='estimation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_estimation_temp', to='enquiries.temp_estimations'),
        ),
        migrations.AddField(
            model_name='temp_estimationnotes',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_estimationnotes',
            name='main_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_parent_replay', to='enquiries.temp_estimationnotes'),
        ),
        migrations.AddField(
            model_name='temp_estimationnotes',
            name='read_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimation_note_read_by_temp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_enquiryspecifications',
            name='aluminium_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enq_spec_system_temp', to='product_master.product'),
        ),
        migrations.AddField(
            model_name='temp_enquiryspecifications',
            name='aluminium_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enquiry_specif_category_temp', to='product_parts.profile_kit'),
        ),
        migrations.AddField(
            model_name='temp_enquiryspecifications',
            name='aluminium_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enquiry_specification_temp', to='profiles.profilemastertype'),
        ),
        migrations.AddField(
            model_name='temp_enquiryspecifications',
            name='aluminium_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enq_spec_system_temp', to='brands.categorybrands'),
        ),
        migrations.AddField(
            model_name='temp_enquiryspecifications',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiry_specif_category_temp', to='Categories.category'),
        ),
        migrations.AddField(
            model_name='temp_enquiryspecifications',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_enq_specification_temp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_enquiryspecifications',
            name='estimation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estimation_spe_specification_temp', to='enquiries.temp_estimations'),
        ),
        migrations.AddField(
            model_name='temp_enquiryspecifications',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_enquiryspecifications',
            name='panel_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enqui_panel_barnd_temp', to='panels_and_others.panelmasterbrands'),
        ),
        migrations.AddField(
            model_name='temp_enquiryspecifications',
            name='panel_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enqui_panel_material_temp', to='panels_and_others.panelmasterbase'),
        ),
        migrations.AddField(
            model_name='temp_enquiryspecifications',
            name='panel_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enq_spec_panel_product_temp', to='product_master.product'),
        ),
        migrations.AddField(
            model_name='temp_enquiryspecifications',
            name='panel_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enqui_panel_series_temp', to='panels_and_others.panelmasterseries'),
        ),
        migrations.AddField(
            model_name='temp_enquiryspecifications',
            name='panel_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enqui_panel_specification_temp', to='panels_and_others.panelmasterspecifications'),
        ),
        migrations.AddField(
            model_name='temp_enquiryspecifications',
            name='surface_finish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enquiry_specification_surface_finish_temp', to='pricing_master.surface_finish_kit'),
        ),
        migrations.AddField(
            model_name='pricing_summary',
            name='estimation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_summary_estimation', to='enquiries.estimations'),
        ),
        migrations.AddField(
            model_name='estimations',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_estimation_tab', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimations',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimation_enquiry', to='enquiries.enquiries'),
        ),
        migrations.AddField(
            model_name='estimations',
            name='inherited_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimation_inherited_revision', to='estimations.estimationversions'),
        ),
        migrations.AddField(
            model_name='estimations',
            name='inherited_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimation_inherited_version', to='estimations.estimationmaniversion'),
        ),
        migrations.AddField(
            model_name='estimations',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimations',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimation_version', to='estimations.estimationversions'),
        ),
        migrations.AddField(
            model_name='estimationnotes',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_estimation_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimationnotes',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_enquiry', to='enquiries.enquiries'),
        ),
        migrations.AddField(
            model_name='estimationnotes',
            name='estimation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_estimation', to='enquiries.estimations'),
        ),
        migrations.AddField(
            model_name='estimationnotes',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimationnotes',
            name='main_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_replay', to='enquiries.estimationnotes'),
        ),
        migrations.AddField(
            model_name='estimationnotes',
            name='read_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimation_note_read_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiryuser',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_active_time', to='enquiries.enquiries'),
        ),
        migrations.AddField(
            model_name='enquiryuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiryspecifications',
            name='aluminium_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enq_spec_system', to='product_master.product'),
        ),
        migrations.AddField(
            model_name='enquiryspecifications',
            name='aluminium_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enquiry_specif_category', to='product_parts.profile_kit'),
        ),
        migrations.AddField(
            model_name='enquiryspecifications',
            name='aluminium_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enquiry_specification', to='profiles.profilemastertype'),
        ),
        migrations.AddField(
            model_name='enquiryspecifications',
            name='aluminium_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enq_spec_system', to='brands.categorybrands'),
        ),
        migrations.AddField(
            model_name='enquiryspecifications',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiry_specif_category', to='Categories.category'),
        ),
        migrations.AddField(
            model_name='enquiryspecifications',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_enq_specification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiryspecifications',
            name='estimation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estimation_spe_specification', to='enquiries.estimations'),
        ),
        migrations.AddField(
            model_name='enquiryspecifications',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiryspecifications',
            name='panel_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enqui_panel_barnd', to='panels_and_others.panelmasterbrands'),
        ),
        migrations.AddField(
            model_name='enquiryspecifications',
            name='panel_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enqui_panel_material', to='panels_and_others.panelmasterbase'),
        ),
        migrations.AddField(
            model_name='enquiryspecifications',
            name='panel_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enq_spec_panel_product', to='product_master.product'),
        ),
        migrations.AddField(
            model_name='enquiryspecifications',
            name='panel_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enqui_panel_series', to='panels_and_others.panelmasterseries'),
        ),
        migrations.AddField(
            model_name='enquiryspecifications',
            name='panel_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enqui_panel_specification', to='panels_and_others.panelmasterspecifications'),
        ),
        migrations.AddField(
            model_name='enquiryspecifications',
            name='surface_finish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enquiry_specification_surface_finish', to='pricing_master.surface_finish_kit'),
        ),
        migrations.AddField(
            model_name='enquiry_log',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_log_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry_log',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_log', to='enquiries.enquiries'),
        ),
        migrations.AddField(
            model_name='enquiry_log',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry_discontinued_history',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_discontinued_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry_discontinued_history',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_discontinued_user', to='enquiries.enquiries'),
        ),
        migrations.AddField(
            model_name='enquiries',
            name='additional_and_labour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='additional_and_labour_enquiry', to='pricing_master.additionalandlabourpricemaster'),
        ),
        migrations.AddField(
            model_name='enquiries',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiry_company', to='companies.companies'),
        ),
        migrations.AddField(
            model_name='enquiries',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_enquiry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiries',
            name='customers',
            field=models.ManyToManyField(to='customers.Customers'),
        ),
        migrations.AddField(
            model_name='enquiries',
            name='enquiry_members',
            field=models.ManyToManyField(related_name='enquiry_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiries',
            name='industry_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiry_industry_type1', to='industry_type.industrytypemodal'),
        ),
        migrations.AddField(
            model_name='enquiries',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiries',
            name='main_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enquiry_main_customer', to='customers.customers'),
        ),
        migrations.AddField(
            model_name='enquiries',
            name='pricing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing_master.pricemaster'),
        ),
        migrations.AddField(
            model_name='enquiries',
            name='sealant_pricing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing_master.sealantpricemaster'),
        ),
        migrations.AddField(
            model_name='enquiries',
            name='surface_finish_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enquiey_surface_finish_price', to='pricing_master.surface_finish_master'),
        ),
        migrations.AddField(
            model_name='enquiries',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enquiry_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
