# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileMasterSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_master_series', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'amoeba__ProfileMasterSeries',
            },
        ),
        migrations.CreateModel(
            name='ProfileMasterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'amoeba__ProfileMasterType',
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('profile_code', models.CharField(blank=True, max_length=255, null=True)),
                ('thickness', models.CharField(blank=True, max_length=255, null=True)),
                ('weight_per_lm', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('profile_enable', models.BooleanField(default=True, help_text='UnCheck To Disable The Profile.')),
            ],
            options={
                'db_table': 'amoeba__Profiles',
            },
        ),
    ]
