# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0002_initial'),
        ('profiles', '0001_initial'),
        ('profile_types', '0002_initial'),
        ('Categories', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_parts', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profiles',
            name='profile_master_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_master_part', to='product_parts.parts'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='profile_master_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_brand', to='profiles.profilemasterseries'),
        ),
        migrations.AddField(
            model_name='profilemastertype',
            name='profile_master_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_matser_category', to='brands.categorybrands'),
        ),
        migrations.AddField(
            model_name='profilemastertype',
            name='profile_master_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_matser_category', to='Categories.category'),
        ),
        migrations.AddField(
            model_name='profilemastertype',
            name='profile_master_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_matser_type', to='profile_types.profile_types'),
        ),
        migrations.AddField(
            model_name='profilemasterseries',
            name='profile_master_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_matser_types', to='profiles.profilemastertype'),
        ),
    ]
