# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopfloors', '0001_initial'),
        ('projects', '0001_initial'),
        ('product_master', '0002_initial'),
        ('enquiries', '0002_initial'),
        ('addon_master', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0002_companies_last_modified_by'),
        ('surface_finish', '0001_initial'),
        ('associated_product', '0002_initial'),
        ('estimations', '0002_initial'),
        ('accessories_kit', '0003_initial'),
        ('panels_and_others', '0002_initial'),
        ('customers', '0002_initial'),
        ('Workstations', '0002_initial'),
        ('product_parts', '0003_initial'),
        ('vehicles_and_drivers', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('pricing_master', '0003_initial'),
        ('brands', '0002_initial'),
        ('UoM', '0002_initial'),
        ('profiles', '0002_initial'),
        ('Categories', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation_history',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_productworkstation_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workstation_history',
            name='workstation_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productworkstation_history_main', to='projects.workstation_data'),
        ),
        migrations.AddField(
            model_name='workstation_data',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_productworkstation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workstation_data',
            name='eps_product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eps_product_workstation', to='projects.eps_products'),
        ),
        migrations.AddField(
            model_name='workstation_data',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workstation_data',
            name='prev_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_workstation_product_id', to='projects.workstation_data'),
        ),
        migrations.AddField(
            model_name='workstation_data',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_productworkstation', to='projects.eps_shopfloor_main_products'),
        ),
        migrations.AddField(
            model_name='workstation_data',
            name='workstation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productworkstation', to='Workstations.workstations'),
        ),
        migrations.AddField(
            model_name='workstation_associated_products_data',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_associated_productworkstation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workstation_associated_products_data',
            name='eps_product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eps_associated_product_workstation', to='projects.eps_products'),
        ),
        migrations.AddField(
            model_name='workstation_associated_products_data',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workstation_associated_products_data',
            name='prev_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_workstation_product_id_associated', to='projects.workstation_associated_products_data'),
        ),
        migrations.AddField(
            model_name='workstation_associated_products_data',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_associated_productworkstation', to='projects.eps_associated_sub_products'),
        ),
        migrations.AddField(
            model_name='workstation_associated_products_data',
            name='workstation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='associated_productworkstation', to='Workstations.workstations'),
        ),
        migrations.AddField(
            model_name='workstation_associated_product_history',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_associatedproductworkstation_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workstation_associated_product_history',
            name='workstation_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='associated_productworkstation_history_main', to='projects.workstation_associated_products_data'),
        ),
        migrations.AddField(
            model_name='wcrproducts',
            name='wcr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_wcr', to='projects.projectwcr'),
        ),
        migrations.AddField(
            model_name='wcrproducts',
            name='wcr_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_wcr_product', to='projects.salesorderitems'),
        ),
        migrations.AddField(
            model_name='temp_eps_products',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eps_temp_created', to='projects.projectcontractitems'),
        ),
        migrations.AddField(
            model_name='temp_eps_products',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eps_temp_product_project', to='projects.projectsmodel'),
        ),
        migrations.AddField(
            model_name='shopfloor_doc',
            name='eps_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eps_shopfloor_attachment', to='projects.eps_shopfloors'),
        ),
        migrations.AddField(
            model_name='schedule_product',
            name='eps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eps_scheduld_products', to='projects.eps_main'),
        ),
        migrations.AddField(
            model_name='schedule_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_product', to='projects.eps_shopfloor_main_products'),
        ),
        migrations.AddField(
            model_name='salessecondarysepcpanels',
            name='panel_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_sec_spec_panel_barnd', to='panels_and_others.panelmasterbrands'),
        ),
        migrations.AddField(
            model_name='salessecondarysepcpanels',
            name='panel_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_sec_spec_panel_category', to='Categories.category'),
        ),
        migrations.AddField(
            model_name='salessecondarysepcpanels',
            name='panel_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_sec_spec_panel_product', to='product_master.product'),
        ),
        migrations.AddField(
            model_name='salessecondarysepcpanels',
            name='panel_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_sec_spec_panel_series', to='panels_and_others.panelmasterseries'),
        ),
        migrations.AddField(
            model_name='salessecondarysepcpanels',
            name='panel_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_sec_spec_panel_specification', to='panels_and_others.panelmasterspecifications'),
        ),
        migrations.AddField(
            model_name='salessecondarysepcpanels',
            name='specifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_sec_spec_panels', to='projects.salesorderspecification'),
        ),
        migrations.AddField(
            model_name='salesorderspecification',
            name='aluminium_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_spec_system', to='product_master.product'),
        ),
        migrations.AddField(
            model_name='salesorderspecification',
            name='aluminium_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_specif_category', to='product_parts.profile_kit'),
        ),
        migrations.AddField(
            model_name='salesorderspecification',
            name='aluminium_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_specification', to='profiles.profilemastertype'),
        ),
        migrations.AddField(
            model_name='salesorderspecification',
            name='aluminium_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_spec_system', to='brands.categorybrands'),
        ),
        migrations.AddField(
            model_name='salesorderspecification',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_specif_category', to='Categories.category'),
        ),
        migrations.AddField(
            model_name='salesorderspecification',
            name='panel_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_panel_barnd', to='panels_and_others.panelmasterbrands'),
        ),
        migrations.AddField(
            model_name='salesorderspecification',
            name='panel_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_panel_material', to='panels_and_others.panelmasterbase'),
        ),
        migrations.AddField(
            model_name='salesorderspecification',
            name='panel_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_spec_panel_product', to='product_master.product'),
        ),
        migrations.AddField(
            model_name='salesorderspecification',
            name='panel_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_panel_series', to='panels_and_others.panelmasterseries'),
        ),
        migrations.AddField(
            model_name='salesorderspecification',
            name='panel_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_panel_specification', to='panels_and_others.panelmasterspecifications'),
        ),
        migrations.AddField(
            model_name='salesorderspecification',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_spec_data', to='projects.projectsmodel'),
        ),
        migrations.AddField(
            model_name='salesorderspecification',
            name='reference_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_ref_specification', to='enquiries.enquiryspecifications'),
        ),
        migrations.AddField(
            model_name='salesorderspecification',
            name='surface_finish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_specification_surface_finish', to='pricing_master.surface_finish_kit'),
        ),
        migrations.AddField(
            model_name='salesorderspecification',
            name='surface_finish_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_specification_surface_finish_color', to='surface_finish.surfacefinishcolors'),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorder_item_brand', to='brands.categorybrands'),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_building', to='projects.epsbuildingsmodel'),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesorderitem_category', to='Categories.category'),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='elevation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_elevation', to='projects.elevationmodel'),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_floor', to='projects.floormodel'),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.salesorderitems'),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='panel_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorder_product_panel_brand', to='panels_and_others.panelmasterbrands'),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='panel_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorder_glass_product', to='product_master.product'),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='panel_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorder_product_panel_series', to='panels_and_others.panelmasterseries'),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorder_product', to='product_master.product'),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='ref_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_ref_pro', to='estimations.estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='sales_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_group', to='projects.salesordergroups'),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorder_product_series', to='product_parts.profile_kit'),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='specification_Identifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorder_specification_identifier', to='projects.salesorderspecification'),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorder_product_suppliers', to='suppliers.suppliers'),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='surface_finish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_product_surface_finish', to='pricing_master.surface_finish_kit'),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorder_product_uom', to='UoM.uom'),
        ),
        migrations.AddField(
            model_name='salesorderinfill',
            name='infill_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_group_infill_specifi', to='panels_and_others.panelmasterspecifications'),
        ),
        migrations.AddField(
            model_name='salesorderinfill',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_item_infill', to='projects.salesorderitems'),
        ),
        migrations.AddField(
            model_name='salesordergroups',
            name='enquiry_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_group_enquiry', to='enquiries.enquiries'),
        ),
        migrations.AddField(
            model_name='salesordergroups',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salesorder_group_data', to='projects.projectsmodel'),
        ),
        migrations.AddField(
            model_name='salesorderaddons',
            name='addons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_addons', to='addon_master.addons'),
        ),
        migrations.AddField(
            model_name='salesorderaddons',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_item_addons', to='projects.salesorderitems'),
        ),
        migrations.AddField(
            model_name='salesorderaccessories',
            name='accessory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_item_accessory_kit', to='accessories_kit.accessorieskititem'),
        ),
        migrations.AddField(
            model_name='salesorderaccessories',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_item_accessory', to='projects.salesorderitems'),
        ),
        migrations.AddField(
            model_name='qaqc_ratinghistory',
            name='infill_product_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qaqc_product_process_item_infill', to='projects.qaqc_infill_products'),
        ),
        migrations.AddField(
            model_name='qaqc_ratinghistory',
            name='product_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qaqc_product_process_item', to='projects.eps_product_details'),
        ),
        migrations.AddField(
            model_name='qaqc_ratinghistory',
            name='qaqc_associated_process_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qaqc_associated_product_history', to='projects.qaqc_associated_product_history'),
        ),
        migrations.AddField(
            model_name='qaqc_ratinghistory',
            name='qaqc_process_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qaqc_product_history', to='projects.qaqc_main_product_history'),
        ),
        migrations.AddField(
            model_name='qaqc_ratinghistory',
            name='qaqc_process_infill_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qaqc_product_infill_history', to='projects.qaqc_infill_history'),
        ),
        migrations.AddField(
            model_name='qaqc_main_product_history',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qaqc_mainproduct_history_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qaqc_main_product_history',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qaqc_mainproduct_history', to='projects.workstation_data'),
        ),
        migrations.AddField(
            model_name='qaqc_infill_products',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qaqc_infill_product', to='projects.eps_outsource_items'),
        ),
        migrations.AddField(
            model_name='qaqc_infill_history',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qaqc_infillproduct_history_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qaqc_infill_history',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qaqc_infillproduct_history', to='projects.qaqc_infill_products'),
        ),
        migrations.AddField(
            model_name='qaqc_associated_product_history',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qaqc_associatedproduct_history_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qaqc_associated_product_history',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qaqc_associatedproduct_history', to='projects.workstation_associated_products_data'),
        ),
        migrations.AddField(
            model_name='projectwcr',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectwcr',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectwcr',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_wcr', to='projects.projectsmodel'),
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='project_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_customer', to='customers.customers'),
        ),
        migrations.AddField(
            model_name='projectsepcificationsapproval',
            name='approve_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_approved_type', to='projects.projectapprovaltypes'),
        ),
        migrations.AddField(
            model_name='projectsepcificationsapproval',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_approved_spec', to='projects.salesorderspecification'),
        ),
        migrations.AddField(
            model_name='projectsepcificationsapproval',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_approved_type_status', to='projects.projectapprovalstatus'),
        ),
        migrations.AddField(
            model_name='projectinvoicingproducts',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_invoice', to='projects.projectinvoices'),
        ),
        migrations.AddField(
            model_name='projectinvoicingproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_invoice_product', to='projects.salesorderitems'),
        ),
        migrations.AddField(
            model_name='projectinvoicingproducts',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_product_project', to='projects.projectsmodel'),
        ),
        migrations.AddField(
            model_name='projectinvoicingpercentage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_percentage_project', to='projects.projectsmodel'),
        ),
        migrations.AddField(
            model_name='projectinvoices',
            name='bill_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_invoice_customer', to='customers.customers'),
        ),
        migrations.AddField(
            model_name='projectinvoices',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comapny_invoices', to='companies.companies'),
        ),
        migrations.AddField(
            model_name='projectinvoices',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectinvoices',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_invoices', to='projects.projectsmodel'),
        ),
        migrations.AddField(
            model_name='projectinstalledquantity',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installed_qunatity_product', to='projects.salesorderitems'),
        ),
        migrations.AddField(
            model_name='projectinstalledquantity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_installed_qunatity', to='projects.projectsmodel'),
        ),
        migrations.AddField(
            model_name='projectinstalledquantity',
            name='wcr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wcr_qunatity_installation', to='projects.projectwcr'),
        ),
        migrations.AddField(
            model_name='projectestimations',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_project_enquiry', to='enquiries.enquiries'),
        ),
        migrations.AddField(
            model_name='projectestimations',
            name='estimations_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimations_version_id', to='enquiries.estimations'),
        ),
        migrations.AddField(
            model_name='projectestimations',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_project_data', to='projects.projectsmodel'),
        ),
        migrations.AddField(
            model_name='projectestimations',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_quotation', to='estimations.quotations'),
        ),
        migrations.AddField(
            model_name='projectdeliveryquantity',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_qunatity_product', to='projects.salesorderitems'),
        ),
        migrations.AddField(
            model_name='projectdeliveryquantity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_delivery_qunatity', to='projects.projectsmodel'),
        ),
        migrations.AddField(
            model_name='projectdeliveryquantity',
            name='wcr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wcr_qunatity_delivery', to='projects.projectwcr'),
        ),
        migrations.AddField(
            model_name='projectdeductionpercentage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deduction_percentage_project', to='projects.projectsmodel'),
        ),
        migrations.AddField(
            model_name='projectcontractitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_contract_item', to='projects.salesorderitems'),
        ),
        migrations.AddField(
            model_name='projectcontractitems',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='projects.projectsmodel'),
        ),
        migrations.AddField(
            model_name='outsource_receive_recode',
            name='received_items',
            field=models.ManyToManyField(to='projects.Eps_Outsource_items'),
        ),
        migrations.AddField(
            model_name='outsource_receive_items',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outsource_recived_products', to='projects.eps_outsource_items'),
        ),
        migrations.AddField(
            model_name='outsource_receive_items',
            name='received_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outsource_recived_batch', to='projects.outsource_receive_recode'),
        ),
        migrations.AddField(
            model_name='inspection_history',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_history_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection_history',
            name='dn_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_history_dn', to='projects.delivery_note'),
        ),
        migrations.AddField(
            model_name='inspection_history',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='infillschedule',
            name='eps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eps_infill_scheduld_products', to='projects.eps_main'),
        ),
        migrations.AddField(
            model_name='infillschedule',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='infill_scheduled_product', to='projects.eps_products'),
        ),
        migrations.AddField(
            model_name='floormodel',
            name='elevation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='elevation_floor', to='projects.elevationmodel'),
        ),
        migrations.AddField(
            model_name='fabrication_attachments',
            name='eps_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eps_product_fabrication', to='projects.eps_products'),
        ),
        migrations.AddField(
            model_name='epsbuildingsmodel',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='building_eps_project', to='projects.projectsmodel'),
        ),
        migrations.AddField(
            model_name='eps_shopfloors',
            name='eps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eps_shopfloor_data', to='projects.eps_main'),
        ),
        migrations.AddField(
            model_name='eps_shopfloors',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eps_shopfloor_product', to='projects.eps_products'),
        ),
        migrations.AddField(
            model_name='eps_shopfloors',
            name='shopfloor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eps_associated_shopfloor', to='shopfloors.shopfloors'),
        ),
        migrations.AddField(
            model_name='eps_shopfloor_main_products',
            name='main_products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eps_shopfloor_main_product', to='projects.eps_product_details'),
        ),
        migrations.AddField(
            model_name='eps_shopfloor_associated_products',
            name='main_products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eps_shopfloor_associated_main_product', to='projects.eps_associated_sub_products'),
        ),
        migrations.AddField(
            model_name='eps_qaqc',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_eps_qaqc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eps_qaqc',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eps_qaqc',
            name='panel_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qaqc_panel_product', to='projects.eps_products'),
        ),
        migrations.AddField(
            model_name='eps_qaqc',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qaqc_product', to='projects.schedule_product'),
        ),
        migrations.AddField(
            model_name='eps_products_for_delivery',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_delivery_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eps_products_for_delivery',
            name='outsourced_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outsourced_product_in_delivery', to='projects.qaqc_infill_products'),
        ),
        migrations.AddField(
            model_name='eps_products_for_delivery',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_for_delivery', to='projects.schedule_product'),
        ),
        migrations.AddField(
            model_name='eps_products',
            name='created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eps_product_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eps_products',
            name='eps_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eps_related_to_product', to='projects.eps_main'),
        ),
        migrations.AddField(
            model_name='eps_products',
            name='eps_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eps_product_item', to='projects.projectcontractitems'),
        ),
        migrations.AddField(
            model_name='eps_products',
            name='eps_product_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eps_product_details_main', to='projects.eps_product_details'),
        ),
        migrations.AddField(
            model_name='eps_products',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eps_product_project', to='projects.projectsmodel'),
        ),
        migrations.AddField(
            model_name='eps_product_details',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eps_product_main', to='projects.eps_products'),
        ),
        migrations.AddField(
            model_name='eps_product_details',
            name='product_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eps_product_details', to='product_parts.parts'),
        ),
        migrations.AddField(
            model_name='eps_outsourced_data',
            name='eps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outsource_eps', to='projects.eps_main'),
        ),
        migrations.AddField(
            model_name='eps_outsourced_data',
            name='outsource_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outsource_suppliers', to='suppliers.suppliers'),
        ),
        migrations.AddField(
            model_name='eps_outsourced_data',
            name='products',
            field=models.ManyToManyField(to='projects.Eps_Outsource_items'),
        ),
        migrations.AddField(
            model_name='eps_outsource_items',
            name='infill_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eps_production_items', to='projects.eps_infill_details'),
        ),
        migrations.AddField(
            model_name='eps_outsource_items',
            name='out_source_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eps_out_source_batch', to='projects.eps_outsourced_data'),
        ),
        migrations.AddField(
            model_name='eps_main',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eps_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eps_main',
            name='eps_products',
            field=models.ManyToManyField(to='projects.Eps_Products'),
        ),
        migrations.AddField(
            model_name='eps_main',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eps_main',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eps_project', to='projects.projectsmodel'),
        ),
        migrations.AddField(
            model_name='eps_infill_temp',
            name='eps_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temp_eps_infill_main_ref', to='projects.eps_main'),
        ),
        migrations.AddField(
            model_name='eps_infill_temp',
            name='infill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eps_infill_temp', to='projects.salessecondarysepcpanels'),
        ),
        migrations.AddField(
            model_name='eps_infill_temp',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eps_infill_main_temp', to='projects.eps_products'),
        ),
        migrations.AddField(
            model_name='eps_infill_details',
            name='eps_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eps_infill_main_ref', to='projects.eps_main'),
        ),
        migrations.AddField(
            model_name='eps_infill_details',
            name='infill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eps_infill', to='projects.salessecondarysepcpanels'),
        ),
        migrations.AddField(
            model_name='eps_infill_details',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eps_infill_main', to='projects.eps_products'),
        ),
        migrations.AddField(
            model_name='eps_associated_sub_products',
            name='main_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Original_associated_product_eps', to='projects.eps_product_details'),
        ),
        migrations.AddField(
            model_name='eps_associated_products',
            name='eps_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eps_product_associated', to='projects.eps_products'),
        ),
        migrations.AddField(
            model_name='eps_associated_products',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eps_associated', to='projects.eps_product_details'),
        ),
        migrations.AddField(
            model_name='elevationmodel',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='building_evevation', to='projects.epsbuildingsmodel'),
        ),
        migrations.AddField(
            model_name='deliverynotecart',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dn_cart_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverynotecart',
            name='temp_dn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_dn', to='projects.delivery_note'),
        ),
        migrations.AddField(
            model_name='delivery_product_cart_main',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_delivery_products_cart_main', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery_product_cart_main',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_for_delivery_cart_main', to='projects.workstation_data'),
        ),
        migrations.AddField(
            model_name='delivery_product_cart_infill',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_delivery_products_cart_infill', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery_product_cart_infill',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_for_delivery_cart_infill', to='projects.qaqc_infill_products'),
        ),
        migrations.AddField(
            model_name='delivery_product_cart_associated',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_delivery_products_cart_associated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery_product_cart_associated',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_for_delivery_cart_associated', to='projects.workstation_associated_products_data'),
        ),
        migrations.AddField(
            model_name='delivery_note',
            name='associated_product',
            field=models.ManyToManyField(to='projects.Workstation_Associated_Products_Data'),
        ),
        migrations.AddField(
            model_name='delivery_note',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_delivery_note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery_note',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_driver', to='vehicles_and_drivers.drivers'),
        ),
        migrations.AddField(
            model_name='delivery_note',
            name='eps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_note_eps', to='projects.eps_main'),
        ),
        migrations.AddField(
            model_name='delivery_note',
            name='infill_product',
            field=models.ManyToManyField(to='projects.QAQC_infill_Products'),
        ),
        migrations.AddField(
            model_name='delivery_note',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery_note',
            name='main_product',
            field=models.ManyToManyField(to='projects.Workstation_Data'),
        ),
        migrations.AddField(
            model_name='delivery_note',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_vehicle', to='vehicles_and_drivers.vehicles'),
        ),
        migrations.AddField(
            model_name='cumulativeinvoiceproduct',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_cumulative_invoice', to='projects.projectinvoices'),
        ),
        migrations.AddField(
            model_name='cumulativeinvoiceproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_cumulative_invoice_product', to='projects.salesorderitems'),
        ),
        migrations.AddField(
            model_name='cumulativeinvoiceproduct',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_cumulative_product_project', to='projects.projectsmodel'),
        ),
        migrations.AddField(
            model_name='contractitems',
            name='associated_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='associated_product.associatedproducts'),
        ),
        migrations.AddField(
            model_name='contractitems',
            name='project_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_contract', to='projects.projectcontractitems'),
        ),
        migrations.AddField(
            model_name='approvalspecfiles',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_approved_spec_files', to='projects.salesorderspecification'),
        ),
        migrations.AddField(
            model_name='approvalnotes',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_approved_spec_notes', to='projects.salesorderspecification'),
        ),
        migrations.AddField(
            model_name='approvalnotes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_notes_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
