from django.urls import path

from apps.configuration_master import views


urlpatterns = [
    path('configuration_base/', views.configuration_base,
         name="configuration_base"),
#     path('configuration_product_list/<int:pk>/',
#          views.configuration_product_list, name="configuration_product_list"),
#     path('add_config_category/', views.add_config_category,
#          name="add_config_category"),
    path('configuration_brands/<int:pk>/',
         views.configuration_brands, name="configuration_brands"),
    path('configuration_series/<int:pk>/<int:product>/',
         views.configuration_series, name="configuration_series"),
    path('configuration_master/<int:pk>/<int:product>/',
         views.configuration_master, name="configuration_master"),
    path('configuration_master_edit/<int:pk>/',
         views.configuration_master_edit, name="configuration_master_edit"),
    # path('add_configuration/<int:pk>/', views.add_configuration, name="add_configuration"),
#     path('add_configuration_brands/<int:pk>/',
#          views.add_configuration_brands, name="add_configuration_brands"),
#     path('add_configuration_series/<int:pk>/',
#          views.add_configuration_series, name="add_configuration_series"),
#     path('edit_configuration_series/<int:pk>/',
#          views.edit_configuration_series, name="edit_configuration_series"),
    path('add_configuration/<int:pk>/',
         views.add_configuration, name="add_configuration"),


    path('configuration_product_parts_kit/<int:pk>/',
         views.configuration_product_parts_kit, name="configuration_product_parts_kit"),
    path('configuration_product_parts/<int:pk>/',
         views.configuration_product_parts, name="configuration_product_parts"),
    path('configuration_product_parts_kit_edit/<int:pk>/',
         views.configuration_product_parts_kit_edit, name="configuration_product_parts_kit_edit"),
    path('delete_product_parts_kit/<int:pk>/',
         views.delete_product_parts_kit, name="delete_product_parts_kit"),
    path('configuration_product_accessories/<int:pk>/',
         views.configuration_product_accessories, name="configuration_product_accessories"),
    path('configuration_product_accessories_settings/<int:pk>/',
         views.configuration_product_accessories_settings, name="configuration_product_accessories_settings"),
    path('configuration_profile_type_list/<int:pk>/<int:product>/',
         views.configuration_profile_type_list, name="configuration_profile_type_list"),

    path('create_product_profile/<int:pk>/',
         views.create_product_profile, name="create_product_profile"),
    path('edit_product_profile/<int:pk>/',
         views.edit_product_profile, name="edit_product_profile"),
    path('get_product_profile_settings/<int:pk>/<int:profile_series>/',
         views.get_product_profile_settings, name="get_product_profile_settings"),
    path('configuration_pre_defined_prices/<int:pk>/',
         views.configuration_pre_defined_prices, name="configuration_pre_defined_prices"),

    # AJAX url
    path('category_wise_product/<int:pk>/',
         views.category_wise_product, name="category_wise_product"),
    path('get_profile_type/<int:pk>/',
         views.get_profile_type, name="get_profile_type"),
    path('get_profile_series/<int:pk>/',
         views.get_profile_series, name="get_profile_series"),
    path('get_profile_data_config/<int:pk>/',
         views.get_profile_data_config, name="get_profile_data_config"),
    path('get_edit_profile_parts/<int:pk>/<int:profile_id>/',
         views.get_edit_profile_parts, name="get_edit_profile_parts"),
    path('delete_part_item/<int:pk>/',
         views.delete_part_item, name="delete_part_item"),
]
