# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=16, null=True)),
                ('salutation', models.IntegerField(choices=[(1, 'Mr.'), (2, 'Mrs.'), (3, 'Miss'), (4, 'Ms.'), (5, 'Dr.'), (6, 'Prof.'), (7, 'Sir'), (8, 'Madam'), (9, "Ma'am"), (11, 'Eng.'), (12, 'Sheikh'), (13, 'Sheikha')])),
            ],
            options={
                'db_table': 'amoeba__Contacts',
            },
        ),
        migrations.CreateModel(
            name='Customer_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.CharField(blank=True, max_length=225, null=True)),
                ('action', models.IntegerField(blank=True, choices=[(1, 'Create'), (2, 'Update'), (3, 'Delete'), (4, 'Export'), (5, 'Download')], null=True)),
            ],
            options={
                'db_table': 'amoeba__Customer_Log',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('official_email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='customer/image')),
                ('post_code', models.IntegerField(blank=True, null=True)),
                ('customer_type', models.IntegerField(blank=True, choices=[(1, 'Company'), (2, 'Individual')], null=True)),
                ('official_number', models.CharField(max_length=16)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers_country', to='brands.countries')),
            ],
            options={
                'db_table': 'amoeba__Customers',
            },
        ),
    ]
