# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriesKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('kit_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('kit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
            options={
                'db_table': 'amoeba__AccessoriesKit',
            },
        ),
        migrations.CreateModel(
            name='AccessoriesKitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('kit_item_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('kit_item_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('accessory_formula', models.CharField(blank=True, max_length=225, null=True)),
                ('acce_divisions', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'amoeba__AccessoriesKitItem',
            },
        ),
    ]
