# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accessories_kit', '0001_initial'),
        ('accessories_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessorieskititem',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kit_item_accessory', to='accessories_master.accessories'),
        ),
        migrations.AddField(
            model_name='accessorieskititem',
            name='accessory_kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_accessory_kit', to='accessories_kit.accessorieskit'),
        ),
    ]
