# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accessories_kit', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessorieskititem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_accKit_item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessorieskititem',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessorieskit',
            name='accessory_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kit_item_accessorysin_kit', to='product_master.product_accessories'),
        ),
        migrations.AddField(
            model_name='accessorieskit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_acc_kit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessorieskit',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessorieskit',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accessory_kit_product', to='product_master.product'),
        ),
    ]
