# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('addon', models.CharField(max_length=255, unique=True)),
                ('linear_meter', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('sqm', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('unit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'amoeba__Addons',
            },
        ),
    ]
