# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_address', models.CharField(max_length=255)),
                ('company_description', models.CharField(blank=True, max_length=255, null=True)),
                ('comany_number', models.CharField(max_length=16)),
                ('header_img', models.ImageField(blank=True, null=True, upload_to='companies/header_img')),
                ('footer_img', models.ImageField(blank=True, null=True, upload_to='companies/footer_img')),
                ('theme_color', models.CharField(max_length=10)),
                ('compny_logo', models.ImageField(upload_to='companies/logos')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_country', to='brands.countries')),
            ],
            options={
                'db_table': 'amoeba__Companies',
            },
        ),
    ]
