from django.urls import path
from apps.enquiries import views


urlpatterns = [
    path('list_add_enquiries/', views.list_add_enquiries, name="list_add_enquiries"),
    path('create_enquiry/', views.create_enquiry, name="create_enquiry"),
    path('enquiry_profile/<int:pk>/<int:version>/', views.enquiry_profile, name="enquiry_profile"),
    path('enquiry_profile/<int:pk>/', views.enquiry_profile, name="enquiry_profile"),
    path('enquiry_notes/<int:pk>/<int:last_version>/', views.enquiry_notes, name="enquiry_notes"),
    # path('enquiry_profile/<int:pk>/', views.enquiry_profile, name="enquiry_profile"),
    path('start_estimation/<int:pk>/', views.start_estimation, name="start_estimation"),
    path('add_enquiry_specifications/<int:pk>/', views.add_enquiry_specifications, name="add_enquiry_specifications"),
    path('enquiry_settings/<int:pk>/<int:version>/', views.enquiry_settings, name="enquiry_settings"),
    path('enquiry_settings/<int:pk>/', views.enquiry_settings, name="enquiry_settings"),
    path('temp_enquiry_settings/<int:pk>/<int:version>/', views.temp_enquiry_settings, name="temp_enquiry_settings"),
    path('temp_enquiry_settings/<int:pk>/', views.temp_enquiry_settings, name="temp_enquiry_settings"),
    path('product_category_summary/<int:pk>/', views.product_category_summary, name="product_category_summary"),
    # path('create_general_quotation/<int:pk>/<int:version>/', views.create_general_quotation, name="create_general_quotation"),
    # path('create_short_quotation/<int:pk>/<int:version>/', views.create_short_quotation, name="create_short_quotation"),
    # path('fetch_notification_async/<int:user_id>/', views.fetch_notification_async, name="fetch_notification_async"),
    
    # path('general_quotation_preview/<int:pk>/', views.general_quotation_preview, name="general_quotation_preview"),
    # path('short_quotation_preview/<int:pk>/', views.short_quotation_preview, name="short_quotation_preview"),
    path('quotation_list_enquiry/', views.quotation_list_enquiry, name="quotation_list_enquiry"),
    path('quotation_filter/<int:cpny>/', views.quotation_filter, name="quotation_filter"),
    path('cancelled_enquiries/', views.cancelled_enquiries, name="cancelled_enquiries"),
    path('cancelled_enquiries_filter/<int:cpny>/', views.cancelled_enquiries_filter, name="cancelled_enquiries_filter"),
    path('get_panel_products_for_sales_spec/<int:pk>/', views.get_panel_products_for_sales_spec, name="get_panel_products_for_sales_spec"),
    path('get_panel_brand_for_sales_spec/<int:pk>/', views.get_panel_brand_for_sales_spec, name="get_panel_brand_for_sales_spec"),
    
    path('view_quotations/<int:pk>/', views.view_quotations, name="view_quotations"),
    path('view_temp_quotations/<int:pk>/', views.view_temp_quotations, name="view_temp_quotations"),
    path('edit_quotation/<int:pk>/', views.edit_quotation, name="edit_quotation"),
    path('temp_edit_quotation/<int:pk>/', views.temp_edit_quotation, name="temp_edit_quotation"),
    path('approval_list/', views.approval_list, name="approval_list"),
    path('approval_filter/<int:cpny>/', views.approval_filter, name="approval_filter"),
    path('approved_list/', views.approved_list, name="approved_list"),
    path('approved_filter/<int:cpny>/', views.approved_filter, name="approved_filter"),
    path('workin_current_version/<int:pk>/', views.workin_current_version, name="workin_current_version"),
    path('enquiry_filter/<int:pk>/', views.enquiry_filter, name="enquiry_filter"),
    path('enquiry_filter/<int:pk>/<int:cpny>/', views.enquiry_filter, name="enquiry_filter"),
    # path('enquiry_filter/<int:pk>/<int:user>/', views.enquiry_filter, name="enquiry_filter"),
    path('enquiry_filter/<int:pk>/<int:cpny>/<int:user>/', views.enquiry_filter, name="enquiry_filter"),
    
    
    path('product_duplicate/<int:pk>/', views.product_duplicate, name="product_duplicate"),
    path('building_duplicate/<int:pk>/', views.building_duplicate, name="building_duplicate"),
    path('edit_enquiry/<int:pk>/', views.edit_enquiry, name="edit_enquiry"),
    path('delete_enquiry/<int:pk>/', views.delete_enquiry, name="delete_enquiry"),
    # path('edit_enquiry_specifications/<int:pk>/', views.edit_enquiry_specifications, name="edit_enquiry_specifications"),
    path('edit_enq_specifications/<int:pk>/', views.edit_enq_specifications, name="edit_enq_specifications"),
    path('temp_edit_enq_specifications/<int:pk>/', views.temp_edit_enq_specifications, name="temp_edit_enq_specifications"),
    path('delete_enq_specifications/<int:pk>/', views.delete_enq_specifications, name="delete_enq_specifications"),
    path('temp_delete_enq_specifications/<int:pk>/', views.temp_delete_enq_specifications, name="temp_delete_enq_specifications"),
    path('create_revision/<int:pk>/', views.create_revision, name="create_revision"),
    path('create_new_version/<int:pk>/', views.create_new_version, name="create_new_version"),
    path('enquiry_import/<int:pk>/', views.enquiry_import, name="enquiry_import"),
    path('list_revisions/<int:pk>/', views.list_revisions, name="list_revisions"),
    path('delete_enquiry_data/<int:pk>/', views.delete_enquiry_data, name="delete_enquiry_data"),

    path('reopen_estimation/<int:enqu_id>/<int:est_id>/', views.reopen_estimation, name="reopen_estimation"),
    path('new_quotaion_customers/<int:pk>/', views.new_quotaion_customers, name="new_quotaion_customers"),
    path('temp_new_quotaion_customers/<int:pk>/', views.temp_new_quotaion_customers, name="temp_new_quotaion_customers"),
    path('enquiry_xlsx_export/<str:type>/', views.enquiry_xlsx_export, name="enquiry_xlsx_export"),
    
    # temprory table views 
    
    path('tem_enquiry_profile/<int:pk>/<int:version>/', views.tem_enquiry_profile, name="tem_enquiry_profile"),
    path('specification_duplicate/<int:pk>', views.specification_duplicate, name="specification_duplicate"),
    path('temp_specification_duplicate/<int:pk>', views.temp_specification_duplicate, name="temp_specification_duplicate"),
    path('version_submit/<int:pk>/', views.version_submit, name="version_submit"),
    path('temp_add_enquiry_specifications/<int:pk>/', views.temp_add_enquiry_specifications, name="temp_add_enquiry_specifications"),
    path('temp_product_category_summary/<int:pk>/', views.temp_product_category_summary, name="temp_product_category_summary"),
    path('temp_update_product_category_percentage/<int:pk>/', views.temp_update_product_category_percentage, name="temp_update_product_category_percentage"),
    path('clear_temp_data/<int:est_id>/<int:pk>/', views.clear_temp_data, name="clear_temp_data"),
    path('temp_building_duplicate/<int:pk>/', views.temp_building_duplicate, name="temp_building_duplicate"),
    path('temp_product_duplicate/<int:pk>/', views.temp_product_duplicate, name="temp_product_duplicate"),
    # path('temp_create_general_quotation/<int:pk>/<int:version>/', views.temp_create_general_quotation, name="temp_create_general_quotation"),
    # path('temp_general_quotation_preview/<int:pk>/', views.temp_general_quotation_preview, name="temp_general_quotation_preview"),
    # path('temp_create_short_quotation/<int:pk>/<int:version>/', views.temp_create_short_quotation, name="temp_create_short_quotation"),
    # path('temp_short_quotation_preview/<int:pk>/', views.temp_short_quotation_preview, name="temp_short_quotation_preview"),
    path('create_quotation_base/<int:pk>/<int:version>/', views.create_quotation_base, name="create_quotation_base"),
    path('temp_create_quotation_base/<int:pk>/<int:version>/', views.temp_create_quotation_base, name="temp_create_quotation_base"),
    

    # AJAX URL'S
    path('get_alumin_products/<int:pk>/', views.get_alumin_products, name="get_alumin_products"),
    path('get_alumin_brand/<int:pk>/', views.get_alumin_brand, name="get_alumin_brand"),
    path('get_alumin_series/<int:pk>/<int:product>/', views.get_alumin_series, name="get_alumin_series"),
    path('get_panel_brand/<int:pk>/', views.get_panel_brand, name="get_panel_brand"),
    path('get_panel_brand_for_estimation_product/<int:estimation>/<int:pk>/', views.get_panel_brand_for_estimation_product, name="get_panel_brand_for_estimation_product"),
    path('get_panel_brand_for_estimation_product_temp/<int:estimation>/<int:pk>/', views.get_panel_brand_for_estimation_product_temp, name="get_panel_brand_for_estimation_product_temp"),
    path('get_panel_series/<int:pk>/', views.get_panel_series, name="get_panel_series"),
    path('get_panel_series_for_estimation_product/<int:estimation>/<int:pk>/', views.get_panel_series_for_estimation_product, name="get_panel_series_for_estimation_product"),
    path('get_panel_series_for_estimation_product_temp/<int:estimation>/<int:pk>/', views.get_panel_series_for_estimation_product_temp, name="get_panel_series_for_estimation_product_temp"),
    path('get_panel_specification/<int:pk>/', views.get_panel_specification, name="get_panel_specification"),
    path('get_panel_specification_for_estimation_product/<int:estimation>/<int:pk>/', views.get_panel_specification_for_estimation_product, name="get_panel_specification_for_estimation_product"),
    path('get_panel_specification_for_estimation_product/<int:estimation>/<int:pk>/<int:spec>/', views.get_panel_specification_for_estimation_product, name="get_panel_specification_for_estimation_product"),
    path('get_panel_specification_for_estimation_product_temp/<int:estimation>/<int:pk>/', views.get_panel_specification_for_estimation_product_temp, name="get_panel_specification_for_estimation_product_temp"),
    path('get_panel_specification_for_estimation_product_temp/<int:estimation>/<int:pk>/<int:spec>/', views.get_panel_specification_for_estimation_product_temp, name="get_panel_specification_for_estimation_product_temp"),
    path('get_category_dimension/<int:pk>/', views.get_category_dimension, name="get_category_dimension"),
    path('get_series_kg_lm/<int:pk>/', views.get_series_kg_lm, name="get_series_kg_lm"),
    # path('get_settings_data/<int:enq_id>/<int:pk>/', views.get_settings_data, name="get_settings_data"),
    path('estimation_submit/<int:pk>/', views.estimation_submit, name="estimation_submit"),
    path('update_product_category_percentage/<int:pk>/', views.update_product_category_percentage, name="update_product_category_percentage"),
    path('update_product_category_percentage_all/<int:pk>/', views.update_product_category_percentage_all, name="update_product_category_percentage_all"),
    # path('quotation_status/<int:status>/<int:pk>/', views.quotation_status, name="quotation_status"),
    # path('temp_quotation_status/<int:status>/<int:pk>/', views.temp_quotation_status, name="temp_quotation_status"),
    path('get_enquiry_sealant_data/<int:pk>/', views.get_enquiry_sealant_data, name="get_enquiry_sealant_data"),
    path('get_panel_categories_glass/<int:pk>/', views.get_panel_categories_glass, name="get_panel_categories_glass"),
    path('get_panel_categories_panels/<int:pk>/', views.get_panel_categories_panels, name="get_panel_categories_panels"),
    path('get_panel_categories_all/<int:pk>/', views.get_panel_categories_all, name="get_panel_categories_all"),
    path('get_panel_products/<int:pk>/', views.get_panel_products, name="get_panel_products"),
    path('get_specification_details/<int:estimation_id>/<int:pk>/', views.get_specification_details, name="get_specification_details"),
    path('temp_get_specification_details/<int:estimation_id>/<int:pk>/', views.temp_get_specification_details, name="temp_get_specification_details"),
    path('get_specification_data/<int:pk>/', views.get_specification_data, name="get_specification_data"),
    path('temp_get_specification_data/<int:pk>/', views.temp_get_specification_data, name="temp_get_specification_data"),
    path('get_customer_data/<int:pk>/<int:quotation_id>/', views.get_customer_data, name="get_customer_data"),
    path('get_customer_data/<int:pk>/<int:quotation_id>/<int:temp>/', views.get_customer_data, name="get_customer_data"),
    path('get_alumin_specification/<int:pk>/<int:product>/', views.get_alumin_specification, name="get_alumin_specification"),
    path('open_enquiry/<int:pk>/<int:version>/', views.open_enquiry, name="open_enquiry"),
    path('open_enquiry/<int:pk>/', views.open_enquiry, name="open_enquiry"),
    path('general_notes_add/<int:pk>/', views.general_notes_add, name="general_notes_add"),
    path('temp_general_notes_add/<int:pk>/', views.temp_general_notes_add, name="temp_general_notes_add"),
    path('update_general_notes/<int:pk>/', views.update_general_notes, name="update_general_notes"),
    path('temp_update_general_notes/<int:pk>/', views.temp_update_general_notes, name="temp_update_general_notes"),
    # path('quotation_preview/<int:pk>/', views.quotation_preview, name="quotation_preview"),
    # path('quotation_preview/<int:pk>/<int:version>', views.quotation_preview, name="quotation_preview"),
    path('user_filter_enq/<int:pk>/', views.user_filter_enq, name="user_filter_enq"),
    path('user_filter_enq/<int:pk>/<int:status>/', views.user_filter_enq, name="user_filter_enq"),
    path('user_filter_approval_enq/<int:pk>/', views.user_filter_approval_enq, name="user_filter_approval_enq"),
    path('user_filter_approved_enq/<int:pk>/', views.user_filter_approved_enq, name="user_filter_approved_enq"),
    path('user_filter_quotations_enq/<int:pk>/', views.user_filter_quotations_enq, name="user_filter_quotations_enq"),
    path('user_filter_cancelled_enquiries_enq/<int:pk>/', views.user_filter_cancelled_enquiries_enq, name="user_filter_cancelled_enquiries_enq"),
    path('get_alumin_custom_products/<int:pk>/', views.get_alumin_custom_products, name="get_alumin_custom_products"),
    
    path('clear_version/<int:pk>/', views.clear_version, name="clear_version"),
    path('view_timer_log/<int:pk>/', views.view_timer_log, name="view_timer_log"),
    
    path('delete_quotation/<int:pk>/', views.delete_quotation, name="delete_quotation"),
    path('temp_delete_quotation/<int:pk>/', views.temp_delete_quotation, name="temp_delete_quotation"),
    

]
