# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(max_length=255, unique=True)),
                ('one_D', models.BooleanField(blank=True, default=False, null=True)),
                ('two_D', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/image')),
                ('is_glass', models.BooleanField(blank=True, default=False, null=True)),
                ('surface_finish', models.BooleanField(blank=True, default=False, null=True)),
                ('sealant', models.BooleanField(blank=True, default=False, null=True)),
                ('points_to_remember', models.BooleanField(blank=True, default=False, null=True)),
                ('points', models.CharField(blank=True, max_length=1000, null=True)),
                ('enable_internal_sealant', models.BooleanField(default=False)),
                ('enable_external_sealant', models.BooleanField(default=False)),
                ('window_or_door_with_divisions', models.BooleanField(default=False)),
                ('invoice_in_quantity', models.BooleanField(default=False)),
                ('window', models.BooleanField(blank=True, default=False, null=True)),
                ('door', models.BooleanField(blank=True, default=False, null=True)),
                ('is_curtain_wall', models.BooleanField(default=False)),
                ('handrail', models.BooleanField(default=False)),
                ('is_ployamide_gasket', models.BooleanField(blank=True, default=False, null=True)),
                ('is_transom_gasket', models.BooleanField(blank=True, default=False, null=True)),
                ('is_mullion_gasket', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'amoeba__Categories',
            },
        ),
    ]
