# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Categories', '0001_initial'),
        ('sealant_types', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='external_sealant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_external_sealant', to='sealant_types.sealant_types'),
        ),
        migrations.AddField(
            model_name='category',
            name='internal_sealant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_internal_sealant', to='sealant_types.sealant_types'),
        ),
        migrations.AddField(
            model_name='category',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='mullion_gasket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_mullion_gasket', to='sealant_types.sealant_types'),
        ),
        migrations.AddField(
            model_name='category',
            name='ployamide_gasket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_ployamide_gasket', to='sealant_types.sealant_types'),
        ),
        migrations.AddField(
            model_name='category',
            name='transom_gasket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_transom_gasket', to='sealant_types.sealant_types'),
        ),
    ]
