# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotations_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('q_type', models.IntegerField(blank=True, choices=[(1, 'General'), (2, 'Short')], null=True)),
                ('master_remarks', models.CharField(blank=True, max_length=2000, null=True)),
                ('short_terms_and_conditions', models.CharField(blank=True, max_length=6000, null=True)),
                ('general_terms_and_conditions', models.CharField(blank=True, max_length=6000, null=True)),
                ('short_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('general_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('master_terms_of_payment', models.CharField(blank=True, max_length=2000, null=True)),
                ('master_exclusions', models.CharField(blank=True, max_length=2000, null=True)),
                ('template_name', models.CharField(max_length=225)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_temp_company', to='companies.companies')),
            ],
            options={
                'db_table': 'amoeba__Quotations_Master',
            },
        ),
    ]
