# Generated by Django 3.2.4 on 2025-04-20 07:27

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationMasterBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'amoeba__ConfigurationMasterBase',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationMasterBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'amoeba__ConfigurationMasterBrands',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationMasterSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'amoeba__ConfigurationMasterSeries',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationsMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True)),
                ('width', models.IntegerField(blank=True, default=0, null=True)),
                ('height', models.IntegerField(blank=True, default=0, null=True)),
                ('unit_area', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True)),
                ('weight_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('price_per_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('min_price_and_area_req', models.BooleanField(default=False)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('markup_percentage_req', models.BooleanField(default=False)),
                ('markup_percentage', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('enable_weight_per_unit', models.BooleanField(blank=True, default=False, null=True)),
                ('enable_price_per_sqm', models.BooleanField(blank=True, default=False, null=True)),
                ('enable_price_per_unit', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'amoeba__ConfigurationsMaster',
            },
        ),
    ]
