# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration_master', '0001_initial'),
        ('product_parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationsmaster',
            name='config_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configurations_series', to='product_parts.profile_kit'),
        ),
    ]
