# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_parts', '0002_initial'),
        ('product_master', '0001_initial'),
        ('brands', '0002_initial'),
        ('configuration_master', '0002_configurationsmaster_config_series'),
        ('Categories', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationsmaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_config_master', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configurationsmaster',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configurationmasterseries',
            name='config_brands',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuration_series_brand', to='configuration_master.configurationmasterbrands'),
        ),
        migrations.AddField(
            model_name='configurationmasterseries',
            name='config_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuration_series', to='product_parts.profile_kit'),
        ),
        migrations.AddField(
            model_name='configurationmasterseries',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_config_series', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configurationmasterseries',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configurationmasterbrands',
            name='brands',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuration_brand', to='brands.categorybrands'),
        ),
        migrations.AddField(
            model_name='configurationmasterbrands',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuration_master_category', to='configuration_master.configurationmasterbase'),
        ),
        migrations.AddField(
            model_name='configurationmasterbrands',
            name='config_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuration_product', to='product_master.product'),
        ),
        migrations.AddField(
            model_name='configurationmasterbrands',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_config_brand', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configurationmasterbrands',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configurationmasterbase',
            name='config_category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Categories.category'),
        ),
        migrations.AddField(
            model_name='configurationmasterbase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_config_master_base', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configurationmasterbase',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
