# Generated by Django 3.2.4 on 2025-04-20 07:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalandLabourPriceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('ideal_overhead', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('ideal_labour', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('minimum_overhead', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('minimum_labour', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
            ],
            options={
                'db_table': 'amoeba__AdditionalandLabourPriceMaster',
            },
        ),
        migrations.CreateModel(
            name='PriceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, choices=[(1, 'International'), (2, 'Local')], null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')])),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('markup', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'amoeba__PriceMaster',
            },
        ),
        migrations.CreateModel(
            name='Sealant_kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('sealant_markup', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'amoeba__Sealant_kit',
            },
        ),
        migrations.CreateModel(
            name='SealantPriceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'amoeba__SealantPriceMaster',
            },
        ),
        migrations.CreateModel(
            name='Surface_finish_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_finish_master_name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'amoeba__Surface_finish_Master',
            },
        ),
        migrations.CreateModel(
            name='Surface_finish_kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_finish_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surface_finish_kit_master', to='pricing_master.surface_finish_master')),
            ],
            options={
                'db_table': 'amoeba__Surface_finish_kit',
            },
        ),
    ]
