# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing_master', '0001_initial'),
        ('surface_finish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surface_finish_kit',
            name='surface_finish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kit_surface_finish', to='surface_finish.surface_finish'),
        ),
    ]
