# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pricing_master', '0002_surface_finish_kit_surface_finish'),
        ('sealant_types', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sealantpricemaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_sealant_price_master', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sealantpricemaster',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sealant_kit',
            name='pricing_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sealant_kit_master', to='pricing_master.sealantpricemaster'),
        ),
        migrations.AddField(
            model_name='sealant_kit',
            name='sealant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='priceing_master_sealant_type', to='sealant_types.sealant_types'),
        ),
        migrations.AddField(
            model_name='pricemaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_price_master', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricemaster',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='additionalandlabourpricemaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_additional_price_master', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='additionalandlabourpricemaster',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
