# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surface_finish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('surface_finish', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'amoeba__Surface_finish',
            },
        ),
        migrations.CreateModel(
            name='SurfaceFinishColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=225)),
                ('surface_finish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='color_surface_finish', to='surface_finish.surface_finish')),
            ],
            options={
                'db_table': 'amoeba__SurfaceFinishColors',
            },
        ),
    ]
