# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, upload_to='product/image')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Published'), (2, 'Draft'), (3, 'Scheduled'), (4, 'Inactive')], null=True)),
                ('installation_hours', models.CharField(blank=True, max_length=20, null=True)),
                ('fabrication_man_hours', models.CharField(blank=True, max_length=20, null=True)),
                ('have_associated_product', models.BooleanField(default=False)),
                ('have_infill', models.BooleanField(default=False)),
                ('assocated_quantity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('infill_quantity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('quotation_product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_type', models.IntegerField(blank=True, choices=[(1, 'Primary'), (2, 'Secondary')], null=True)),
            ],
            options={
                'db_table': 'amoeba__Products',
            },
        ),
        migrations.CreateModel(
            name='Product_Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_accessories_title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'amoeba__Product_Accessories',
            },
        ),
        migrations.CreateModel(
            name='Product_Accessories_Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_formula', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'amoeba__Product_Accessory_kit',
            },
        ),
        migrations.CreateModel(
            name='Product_WorkStations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'amoeba__Product_WorkStations',
            },
        ),
        migrations.CreateModel(
            name='SecondaryProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='secondary_product/image')),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'amoeba__SecondaryProducts',
            },
        ),
    ]
