# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_master', '0001_initial'),
        ('UoM', '0002_initial'),
        ('Workstations', '0002_initial'),
        ('associated_product', '0002_initial'),
        ('Categories', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accessories_master', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondaryproducts',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_secondary_product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secondaryproducts',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Categories.category'),
        ),
        migrations.AddField(
            model_name='secondaryproducts',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UoM.uom'),
        ),
        migrations.AddField(
            model_name='product_workstations',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workshop_product', to='product_master.product'),
        ),
        migrations.AddField(
            model_name='product_workstations',
            name='workstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_workstation', to='Workstations.workstations'),
        ),
        migrations.AddField(
            model_name='product_accessories_kit',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_base_kit_accessory', to='accessories_master.accessories'),
        ),
        migrations.AddField(
            model_name='product_accessories_kit',
            name='product_accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_master.product_accessories'),
        ),
        migrations.AddField(
            model_name='product_accessories',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_master.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='associated_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_associated_product', to='associated_product.associatedproducts'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Categories.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UoM.uom'),
        ),
    ]
