# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categories', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorybrands',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_category_brand', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categorybrands',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brands',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_base_brand', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessoriesbrands',
            name='brands',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_brand_acce', to='brands.brands'),
        ),
        migrations.AddField(
            model_name='accessoriesbrands',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accessory_brand_cat', to='Categories.category'),
        ),
        migrations.AddField(
            model_name='accessoriesbrands',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country_accessory_cat', to='brands.countries'),
        ),
        migrations.AddField(
            model_name='accessoriesbrands',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_accessory_brand', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessoriesbrands',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
