from django.urls import path, re_path
from django.urls import re_path as url
from apps.projects import views, views_2


urlpatterns = [
    path('list_projects/', views.list_projects, name="list_projects"),
    path('create_project/', views.create_project, name="create_project"),
    path('get_project_details/<int:pk>/',
         views.get_project_details, name="get_project_details"),
    path('assign_quotation_to_project/<int:pk>/',
         views.assign_quotation_to_project, name="assign_quotation_to_project"),
    path('project_profile/<int:pk>/',
         views.project_profile, name="project_profile"),
    path('project_scop/<int:pk>/', views.project_scop, name="project_scop"),
    path('project_budgeting/<int:pk>/',
         views.project_budgeting, name="project_budgeting"),
    
    path('project_settings/<int:pk>/', views.project_settings, name="project_settings"),
    path('project_settings/<int:pk>/<int:building_id>/', views.project_settings, name="project_settings"),
    path('project_settings/<int:pk>/<int:building_id>/<int:elevation>/', views.project_settings, name="project_settings"),
    
    path('add_project_settings_invoice_percentage/<int:pk>/',
         views.add_project_settings_invoice_percentage, name="add_project_settings_invoice_percentage"),
    path('add_project_settings_deduction_percentage/<int:pk>/',
         views.add_project_settings_deduction_percentage, name="add_project_settings_deduction_percentage"),
    path('project_accounts/<int:pk>/',
         views.project_accounts, name="project_accounts"),
    path('project_invoices/<int:pk>/',
         views.project_invoices, name="project_invoices"),
    path('create_project_invoice/<int:pk>/',
         views.create_project_invoice, name="create_project_invoice"),
    path('edit_project_invoice/<int:pk>/',
         views.edit_project_invoice, name="edit_project_invoice"),
    path('update_delivery_qunatity/<int:project>/<int:product>/',
         views.update_delivery_qunatity, name="update_delivery_qunatity"),
    path('update_installed_qunatity/<int:project>/<int:product>/',
         views.update_installed_qunatity, name="update_installed_qunatity"),
    path('view_invoice_normal/<int:pk>/',
         views.view_invoice_normal, name="view_invoice_normal"),
    path('edit_product_delete/<int:pk>/',
         views.edit_product_delete, name="edit_product_delete"),
    path('view_project_wcr/<int:pk>/',
         views.view_project_wcr, name="view_project_wcr"),
    path('create_project_wcr/<int:pk>/',
         views.create_project_wcr, name="create_project_wcr"),
    path('view_wcr/<int:pk>/', views.view_wcr, name="view_wcr"),
    path('edit_project_wcr/<int:pk>/',
         views.edit_project_wcr, name="edit_project_wcr"),
    path('delete_wcr_product/<int:pk>/',
         views.delete_wcr_product, name="delete_wcr_product"),
    path('cumulative_invoicing/<int:pk>/',
         views.cumulative_invoicing, name="cumulative_invoicing"),
    path('view_invoice_cumulative/<int:pk>/',
         views.view_invoice_cumulative, name="view_invoice_cumulative"),
    path('edit_project_cumulative_invoice/<int:pk>/',
         views.edit_project_cumulative_invoice, name="edit_project_cumulative_invoice"),
    path('update_project/<int:pk>/', views.update_project, name="update_project"),
#     path('project_contract_items/<int:pk>/',
#          views.project_contract_items, name="project_contract_items"),
    path('convert_to_contract_item/<int:project>/<int:building>/<str:product_data>/',
         views.convert_to_contract_item, name="convert_to_contract_item"),
    path('proccess_quotation/<int:pk>/', views.proccess_quotation, name="proccess_quotation"),
#     path('update_quotation_item/<int:pk>/<int:id>/', views.update_quotation_item, name="update_quotation_item"),
    path('delete_sales_item/<int:pk>/', views.delete_sales_item, name="delete_sales_item"),
    path('sales_item_duplicate/<int:pk>/', views.sales_item_duplicate, name="sales_item_duplicate"),


    # AJAX requests
    path('get_stage_percentage/<int:pk>/',
         views.get_stage_percentage, name="get_stage_percentage"),
    path('get_product_delivery_quantity/<int:project>/<int:pk>/',
         views.get_product_delivery_quantity, name="get_product_delivery_quantity"),
    path('project_accounts_side_view/<int:project>/<int:product>/',
         views.project_accounts_side_view, name="project_accounts_side_view"),
    path('project_lost/<int:q_id>/', views.project_lost, name="project_lost"),
    path('project_eps/<int:pk>/', views.project_eps, name="project_eps"),
    path('create_eps/<int:pk>/', views.create_eps, name="create_eps"),
    path('create_glass_eps/<int:pk>/', views.create_glass_eps, name="create_glass_eps"),
    path('add_eps_item/<int:pk>/', views.add_eps_item, name="add_eps_item"),
    path('add_eps_item_from_model/<int:pk>/', views.add_eps_item_from_model, name="add_eps_item_from_model"),
    path('delete_eps_item/<int:pk>/', views.delete_eps_item, name="delete_eps_item"),
    path('eps_collaps_data/<int:pk>/', views.eps_collaps_data, name="eps_collaps_data"),
    path('glass_eps_collaps_data/<int:pk>/', views.glass_eps_collaps_data, name="glass_eps_collaps_data"),
    path('product_details_delete/<int:pk>/', views_2.product_details_delete, name="product_details_delete"),
    path('product_infill_delete/<int:pk>/', views_2.product_infill_delete, name="product_infill_delete"),
    path('product_temp_infill_delete/<int:pk>/', views_2.product_temp_infill_delete, name="product_temp_infill_delete"),
    path('update_project_settings_invoice_percentage/<int:pk>/', views.update_project_settings_invoice_percentage, 
         name="update_project_settings_invoice_percentage"),
    path('update_project_settings_deduction_percentage/<int:pk>/', views.update_project_settings_deduction_percentage, 
         name="update_project_settings_deduction_percentage"),
    
#     path('download_attachments/<str:path>/', views.download_eps_attachments, name='download_eps_attachments'),
    path('view_eps/<str:eps>/', views.view_eps, name='view_eps'),
    path('view_eps/<str:eps>/<str:product>/', views.view_eps, name='view_eps'),
    path('view_eps_product/<int:pk>/', views.view_eps_product, name='view_eps_product'),
    path('eps_product_view/<str:pk>/', views.eps_product_view, name='eps_product_view'),
    path('eps_view_fabrications/<int:pk>/', views.eps_view_fabrications, name='eps_view_fabrications'),
#     path('fabrication_attachment_upload/<int:pk>/', views.fabrication_attachment_upload, name='fabrication_attachment_upload'),
    path('eps_production_view/<int:pk>/', views.eps_production_view, name='eps_production_view'),
    path('eps_product_product_view/<int:pk>/', views.eps_product_product_view, name='eps_product_product_view'),
    path('infill_outsource_btn/<int:pk>/', views.infill_outsource_btn, name='infill_outsource_btn'),
    path('update_infill_details/<int:pk>/', views.update_infill_details, name='update_infill_details'),
    path('update_infill_details/<int:pk>/<str:type>/', views.update_infill_details, name='update_infill_details'),
    path('infill_delete/<int:pk>/', views.infill_delete, name='infill_delete'),
#     path('infill_delete/<int:pk>/<str:type>/', views.infill_delete, name='infill_delete'),
#     path('set_shopfloortoeps/<int:pk>/<int:eps>/', views.set_shopfloortoeps, name='set_shopfloortoeps'),
    path('eps_outsource_view/<int:eps>/', views.eps_outsource_view, name='eps_outsource_view'),
    path('eps_outsource_view/<int:eps>/<int:product>/', views.eps_outsource_view, name='eps_outsource_view'),
    path('outsource_product/<str:infill>/<int:eps_product>/', views.outsource_product, name='outsource_product'),
#     path('outsource_product/<str:infills>/<int:eps>/<str:type>/', views.outsource_product, name='outsource_product'),
    path('os_recive/<str:items>/<int:eps>/', views.os_recive, name='os_recive'),
#     path('os_recive/<str:items>/<int:eps>/<str:type>/', views.os_recive, name='os_recive'),
    path('received_info/<str:items>/', views.received_info, name='received_info'),
    path('eps_shopfloor_view/<int:pk>/', views.eps_shopfloor_view, name='eps_shopfloor_view'),
    path('shopfloor_product_details/<int:pk>/', views.shopfloor_product_details, name='shopfloor_product_details'),
    path('schedule_product/<int:pk>/', views.schedule_product, name='schedule_product'),
    path('schedule_product_edit/<int:pk>/', views.schedule_product_edit, name='schedule_product_edit'),
    path('schedule_product_edit/<int:pk>/<str:re_path>/', views.schedule_product_edit, name='schedule_product_edit'),
    path('workstaions_view/<int:pk>/', views.workstaions_view, name='workstaions_view'),
    path('workstations_single_view_update/<int:pk>/', views.workstations_single_view_update, name='workstations_single_view_update'),
    path('workstation_product_details/<int:pk>/', views.workstation_product_details, name='workstation_product_details'),
    path('workstation_product_update/<int:pk>/', views.workstation_product_update, name='workstation_product_update'),
    path('workstation_product_update/<int:pk>/<int:associated>/', views.workstation_product_update, name='workstation_product_update'),
    path('workstation_product_update/<int:pk>/<str:type>/', views.workstation_product_update, name='workstation_product_update'),
    path('workstation_product_update/<int:pk>/<int:associated>/<str:type>/', views.workstation_product_update, name='workstation_product_update'),
#     re_path(r'^workstation_product_update/(?P<pk>\d+)(/(?P<associated>\d+))?(/(?P<type>\w+))?/$', views.workstation_product_update, name='workstation_product_update'),
    path('worksation_history/<int:pk>/', views.worksation_history, name='worksation_history'),
    path('worksation_history/<int:pk>/<int:associated>/', views.worksation_history, name='worksation_history'),
    path('skip_workstation/<int:pk>/', views.skip_workstation, name='skip_workstation'),
    path('skip_workstation/<int:pk>/<int:associated>/', views.skip_workstation, name='skip_workstation'),
    
    path('qaqc_view/<int:pk>/', views.qaqc_view, name='qaqc_view'),
    path('qaqc_detail_view/<int:pk>/', views.qaqc_detail_view, name='qaqc_detail_view'),
    path('qaqc_quantity_update/<int:pk>/', views.qaqc_quantity_update, name='qaqc_quantity_update'),
    path('qaqc_quantity_update/<int:pk>/<int:associated>/', views.qaqc_quantity_update, name='qaqc_quantity_update'),
    path('qaqc_quantity_history/<int:pk>/<int:associated>/', views.qaqc_quantity_history, name='qaqc_quantity_history'),
    path('qaqc_quantity_history/<int:pk>/', views.qaqc_quantity_history, name='qaqc_quantity_history'),
    path('qaqc_infill_quantity_update/<int:pk>/', views.qaqc_infill_quantity_update, name='qaqc_infill_quantity_update'),
    path('qaqc_infill_quantity_update/<int:pk>/<str:type>/', views.qaqc_infill_quantity_update, name='qaqc_infill_quantity_update'),
    path('qaqc_infill_quantity_history/<int:pk>/', views.qaqc_infill_quantity_history, name='qaqc_infill_quantity_history'),
    
    path('products_for_delivery_view/<int:eps>/', views.products_for_delivery_view, name='products_for_delivery_view'),
    path('product_for_delivery_details/<int:pk>/', views.product_for_delivery_details, name='product_for_delivery_details'),
    path('delivery_quantity_update/<int:pk>/', views.delivery_quantity_update, name='delivery_quantity_update'),
#     path('delivery_quantity_update/<int:pk>/<str:type>/', views.delivery_quantity_update, name='delivery_quantity_update'),
    path('delivery_quantity_update/<int:pk>/<int:associated>/', views.delivery_quantity_update, name='delivery_quantity_update'),
#     path('delivery_quantity_update/<int:pk>/<int:associated>/<str:type>', views.delivery_quantity_update, name='delivery_quantity_update'),
    path('delivery_infill_quantity_update/<int:pk>/', views.delivery_infill_quantity_update, name='delivery_infill_quantity_update'),
    path('delivery_infill_quantity_update/<int:pk>/<str:type>/', views.delivery_infill_quantity_update, name='delivery_infill_quantity_update'),
    path('cart_delete/<int:pk>/<str:type>/', views.cart_delete, name='cart_delete'),
    path('create_delivery_note/<int:eps>/', views.create_delivery_note, name='create_delivery_note'),
    path('scheduled_deliveries/', views_2.scheduled_deliveries, name='scheduled_deliveries'),
    path('completed_deliveries/', views_2.completed_deliveries, name='completed_deliveries'),
    path('markas_dn_delivered/<int:pk>/', views_2.markas_dn_delivered, name='markas_dn_delivered'),
    path('clear_panel_details/<int:pk>/', views.clear_panel_details, name='clear_panel_details'),
    
    # View_2 urls  
    # EPS consolidated List
    path('eps_consolidated_list/', views_2.eps_consolidated_list, name='eps_consolidated_list'),
    path('eps_consolidated_list/<int:status>/', views_2.eps_consolidated_list, name='eps_consolidated_list'),
    
     
    #  Fabrications
    path('general_fabrications_view/', views_2.general_fabrications_view, name='general_fabrications_view'),
    path('general_fabrications_view/<str:status>/', views_2.general_fabrications_view, name='general_fabrications_view'),
#     path('fabrication_detail_eps_list/<int:pk>/', views_2.fabrication_detail_eps_list, name='fabrication_detail_eps_list'),
#     path('fabrication_details/<int:pk>/', views_2.fabrication_details, name='fabrication_details'),
#     path('fabrication_product_detail_view/<int:pk>/', views_2.fabrication_product_detail_view, name='fabrication_product_detail_view'),
    path('fabrication_multi_attachment/<int:pk>/', views_2.fabrication_multi_attachment, name='fabrication_multi_attachment'),
    
    #  Productions
    path('general_production_view/', views_2.general_production_view, name='general_production_view'),
    path('general_production_view/<int:status>/', views_2.general_production_view, name='general_production_view'),
#     path('productions_detail_eps_list/<int:pk>/', views_2.productions_detail_eps_list, name='productions_detail_eps_list'),
#     path('production_details/<int:pk>/', views_2.production_details, name='production_details'),
#     path('production_product_detail_view/<int:pk>/', views_2.production_product_detail_view, name='production_product_detail_view'),
    path('aluminium_status_update/<int:pk>/', views_2.aluminium_status_update, name='aluminium_status_update'),
    path('alumin_status_short_update/<int:pk>/<int:status>/', views_2.alumin_status_short_update, name='alumin_status_short_update'),
    path('alumin_status_short_update/<int:pk>/<int:status>/<str:re_dir>/', views_2.alumin_status_short_update, name='alumin_status_short_update'),
    path('accessory_status_update/<int:pk>/', views_2.accessory_status_update, name='accessory_status_update'),
    path('accessory_status_short_update/<int:pk>/<int:status>/', views_2.accessory_status_short_update, name='accessory_status_short_update'),
    path('accessory_status_short_update/<int:pk>/<int:status>/<str:re_dir>/', views_2.accessory_status_short_update, name='accessory_status_short_update'),
    path('general_new_infill/<int:pk>/', views_2.general_new_infill, name='general_new_infill'),
    path('general_new_infill/<int:pk>/<str:dirc>/', views_2.general_new_infill, name='general_new_infill'),
    path('product_details_update/<int:pk>/', views_2.product_details_update, name='product_details_update'),
    path('set_shopfloor/<int:pk>/', views_2.set_shopfloor, name='set_shopfloor'),
    path('infill_outsource/<int:pk>/', views_2.infill_outsource, name='infill_outsource'),
    
    #  Outsource 
    path('general_outsource_view/', views_2.general_outsource_view, name='general_outsource_view'),
    path('general_outsource_view/<int:status>/', views_2.general_outsource_view, name='general_outsource_view'),
#     path('outsource_detail_eps_list/<int:pk>/', views_2.outsource_detail_eps_list, name='outsource_detail_eps_list'),
#     path('outsource_details/<int:pk>/', views_2.outsource_details, name='outsource_details'),
#     path('outsource_product_detail_view/<int:pk>/', views_2.outsource_product_detail_view, name='outsource_product_detail_view'),
         
    # Shopfloor
    path('general_shopfloor_view/', views_2.general_shopfloor_view, name='general_shopfloor_view'),
    path('general_shopfloor_view/<int:status>/', views_2.general_shopfloor_view, name='general_shopfloor_view'),
    path('shopfloor_filter/<int:shopfloor>/', views_2.shopfloor_filter, name='shopfloor_filter'),
    path('shopfloor_filter/<int:shopfloor>/<int:status>/', views_2.shopfloor_filter, name='shopfloor_filter'),
    path('shopfloor_projects/<int:pk>/', views_2.shopfloor_projects, name='shopfloor_projects'),
    path('shopfloor_detail_eps_list/<int:pk>/', views_2.shopfloor_detail_eps_list, name='shopfloor_detail_eps_list'),
    path('shopfloor_details/<int:pk>/', views_2.shopfloor_details, name='shopfloor_details'),
    path('shopfloor_product_detail_view/<int:pk>/', views_2.shopfloor_product_detail_view, name='shopfloor_product_detail_view'),
    path('move_to_workstation/<int:pk>/', views_2.move_to_workstation, name='move_to_workstation'),
     
    #  Workstation
    path('general_workstation_view/', views_2.general_workstation_view, name='general_workstation_view'),
    path('workstation_completed/', views_2.workstation_completed, name='workstation_completed'),
    path('workstation_completed/<str:project>/', views_2.workstation_completed, name='workstation_completed'),
    path('workstation_projects/<int:pk>/', views_2.workstation_projects, name='workstation_projects'),
    path('workstation_projects_cmpld/<int:pk>/', views_2.workstation_projects_cmpld, name='workstation_projects_cmpld'),
    path('workstation_projects_cmpld/<int:pk>/<str:project>/', views_2.workstation_projects_cmpld, name='workstation_projects_cmpld'),
    path('workstation_detail_eps_list/<int:pk>/', views_2.workstation_detail_eps_list, name='workstation_detail_eps_list'),
    path('workstation_details/<int:pk>/', views_2.workstation_details, name='workstation_details'),
    path('workstation_product_detail_view/<int:pk>/', views_2.workstation_product_detail_view, name='workstation_product_detail_view'),
    path('workstation_side_data/<int:pk>/', views.workstation_side_data, name='workstation_side_data'),
    path('workstation_side_data_cmpltd/<int:pk>/', views.workstation_side_data_cmpltd, name='workstation_side_data_cmpltd'),
    path('workstations_side_update/', views.workstations_side_update, name='workstations_side_update'),
#     path('workstations_side_update/<int:pk>/<str:associated>/', views.workstations_side_update, name='workstations_side_update'),
         
    #  QAQC 
    path('general_qaqc_view/', views_2.general_qaqc_view, name='general_qaqc_view'),
    path('general_qaqc_view/<int:status>/', views_2.general_qaqc_view, name='general_qaqc_view'),
    path('qaqc_detail_eps_list/<int:pk>/', views_2.qaqc_detail_eps_list, name='qaqc_detail_eps_list'),
    path('qaqc_details/<int:pk>/', views_2.qaqc_details, name='qaqc_details'),
    path('qaqc_product_detail_view/<int:pk>/', views_2.qaqc_product_detail_view, name='qaqc_product_detail_view'),
    
    #  Product For Delivery 
    path('general_product_for_delivery_view/', views_2.general_product_for_delivery_view, name='general_product_for_delivery_view'),
#     path('general_product_for_delivery_view/<int:status>/', views_2.general_product_for_delivery_view, name='general_product_for_delivery_view'),
    path('product_for_delivery_detail_eps_list/<int:pk>/', views_2.product_for_delivery_detail_eps_list, name='product_for_delivery_detail_eps_list'),
    path('general_product_for_delivery_details/<int:pk>/', views_2.general_product_for_delivery_details, name='general_product_for_delivery_details'),
    path('product_for_delivery_product_detail_view/<int:pk>/', views_2.product_for_delivery_product_detail_view, name='product_for_delivery_product_detail_view'),
         
    # Delivery Note 
    path('general_delivery_note_view/', views_2.general_delivery_note_view, name='general_delivery_note_view'),
#     path('project_wise_delivery_eps_list/<int:pk>/', views_2.project_wise_delivery_eps_list, name='project_wise_delivery_eps_list'),
    path('delivery_note_view/<int:pk>/', views_2.delivery_note_view, name='delivery_note_view'),
    path('update_dn_status/<int:pk>/', views_2.update_dn_status, name='update_dn_status'),
    path('print_delivery_note/<int:pk>/', views_2.print_delivery_note, name='print_delivery_note'),
    
    # Inspecion     
    path('inspection_list/', views_2.inspection_list, name='inspection_list'),
    path('inspection_list/<int:project>/', views_2.inspection_list, name='inspection_list'),
    path('inspection_view/<int:pk>/', views.inspection_view, name='inspection_view'),
    path('update_inspect_qty/<int:pk>/<int:product>/', views_2.update_inspect_qty, name='update_inspect_qty'),
    path('inspection_history/<int:pk>/', views_2.inspection_history, name='inspection_history'),
    path('completed_inspection_list/', views_2.completed_inspection_list, name='completed_inspection_list'),
    path('completed_inspection_list/<int:project>/', views_2.completed_inspection_list, name='completed_inspection_list'),
    
    path('product_eps_print/<int:pk>/', views_2.product_eps_print, name='product_eps_print'),
    path('product_eps_print/<int:pk>/<int:types>/', views_2.product_eps_print, name='product_eps_print'),
    path('outsource_print/<int:pk>/', views_2.outsource_print, name='outsource_print'),
    path('eps_print/<int:pk>/', views_2.eps_print, name='eps_print'),
    
    url(r'^download_attachments/(?P<path>.+)/$',views.download_eps_attachments, name='download_eps_attachments'),
    url(r'^download_eps_fabrication/(?P<path>.+)/$',views.download_eps_fabrication, name='download_eps_fabrication'),
    path('get_enquiry_revisions/<int:pk>/', views.get_enquiry_revisions, name='get_enquiry_revisions'),
    path('workstation_quantity_update/<int:pk>/<int:types>/<int:workstation_id>/', views_2.workstation_quantity_update, name='workstation_quantity_update'),
    path('workstation_time_data/<int:pk>/<int:eps_id>/<str:p_type>/', views_2.workstation_time_data, name='workstation_time_data'),
    path('eps_side_details/<int:pk>/', views.eps_side_details, name="eps_side_details"),
    path('eps_side_details/<int:pk>/<int:product>/', views.eps_side_details, name="eps_side_details"),
    path('import_from_scope/<int:pk>/', views.import_from_scope, name="import_from_scope"),
    path('new_sales_item/<int:pk>/', views.new_sales_item, name="new_sales_item"),
    path('update_salesItem/<int:pk>/', views.update_salesItem, name="update_salesItem"),
    path('get_sales_specification_by_category/<int:pk>/<int:project>/', views_2.get_sales_specification_by_category, name="get_sales_specification_by_category"),
    path('get_data_from_sales_spec/<int:pk>/', views_2.get_data_from_sales_spec, name="get_data_from_sales_spec"),
    path('salesItem_specifications/<int:pk>/', views.salesItem_specifications, name="salesItem_specifications"),
    path('project_approvals/<int:pk>/', views.project_approvals, name="project_approvals"),
    
    path('sales_specification_udate/<int:pk>/', views.sales_specification_udate, name="sales_specification_udate"),
    path('enquiry_details/<int:pk>/', views.enquiry_details, name="enquiry_details"),
    path('eps_quotation_view/<int:pk>/', views.eps_quotation_view, name="eps_quotation_view"),
    path('salesorderitem_side_view/<int:pk>/', views.salesorderitem_side_view, name="salesorderitem_side_view"),
    path('add_secondary_product/<int:pk>/', views.add_secondary_product, name="add_secondary_product"),
    path('update_secondary_product/<int:pk>/', views.update_secondary_product, name="update_secondary_product"),
    path('delete_secondary_product/<int:pk>/', views.delete_secondary_product, name="delete_secondary_product"),
    
    path('project_approval_settings/', views.project_approval_settings, name="project_approval_settings"),
    path('add_project_approvaltype/', views.add_project_approvaltype, name="add_project_approvaltype"),
    path('update_project_approvaltype/<int:pk>/', views.update_project_approvaltype, name="update_project_approvaltype"),
    path('delete_project_approvaltype/<int:pk>/', views.delete_project_approvaltype, name="delete_project_approvaltype"),
    path('project_approval_statusadd/', views.project_approval_statusadd, name="project_approval_statusadd"),
    path('project_approval_statusupdate/<int:pk>/', views.project_approval_statusupdate, name="project_approval_statusupdate"),
    path('delete_project_approvalstatus/<int:pk>/', views.delete_project_approvalstatus, name="delete_project_approvalstatus"),
    path('delivery_note_add_cart/<int:pk>/', views_2.delivery_note_add_cart, name="delivery_note_add_cart"),
    path('checkout_dn_cart/<int:pk>/', views_2.checkout_dn_cart, name="checkout_dn_cart"),
    path('remove_from_dn_cart/<int:pk>/', views_2.remove_from_dn_cart, name="remove_from_dn_cart"),
    
    path('delete_specification_secondary_panels/<int:pk>/', views.delete_specification_secondary_panels, name="delete_specification_secondary_panels"),
    path('sales_order_specification_duplicate/<int:pk>/', views.sales_order_specification_duplicate, name="sales_order_specification_duplicate"),
    
    path('get_surfacefinish_color/<int:pk>/', views.get_surfacefinish_color, name="get_surfacefinish_color"),
    path('update_project_approval_status/<int:pk>/<int:status>/', views.update_project_approval_status, name="update_project_approval_status"),
    path('update_approval_notes/<int:pk>/', views.update_approval_notes, name="update_approval_notes"),
    path('eps_history_view/<int:pk>/<int:product>/', views.eps_history_view, name="eps_history_view"),
    path('elevation_assign/<int:pk>/', views_2.elevation_assign, name="elevation_assign"),
    path('get_elevations_list/<int:pk>/', views_2.get_elevations_list, name="get_elevations_list"),
    path('get_floor_list/<int:pk>/', views_2.get_floor_list, name="get_floor_list"),
    path('assign_eps_uoms/<int:pk>/', views_2.assign_eps_uoms, name="assign_eps_uoms"),
    path('sales_product_infill_delete/<int:pk>/', views_2.sales_product_infill_delete, name="sales_product_infill_delete"),
    path('category_wise_filter/<int:project>/', views_2.category_wise_filter, name="category_wise_filter"),
    path('category_wise_filter/<int:project>/<int:pk>/', views_2.category_wise_filter, name="category_wise_filter"),
    
    path('specification_approval_fileupload/<int:pk>/', views_2.specificationApprovalFileUpload, name="specification_approval_fileupload"),
    path('qaqc_functional_parameters/', views.qaqc_functional_parameters, name="qaqc_functional_parameters"),
    path('add_qaqc_param/', views.add_qaqc_param, name="add_qaqc_param"),
    path('update_qaqc_param/<int:pk>/', views.update_qaqc_param, name="update_qaqc_param"),
    path('delete_qaqc_param/<int:pk>/', views.delete_qaqc_param, name="delete_qaqc_param"),
    
]
