# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'amoeba__Designations',
            },
        ),
    ]
