"""
Django settings for amoeba project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""


import os
import pdfkit


try:
    from amoeba.local_settings import *
except Exception:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f^^kd#vqq)9a3xk(dnnik(b+l**vm^lvegh+-xqc2#-(23^suf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '192.168.60.106',
]

# INTERNAL_IPS = [
#     '127.0.0.1',
#     'localhost',
# ]


# Application definition

INSTALLED_APPS = [
    # 'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    # 'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # 'daphne',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # 3rd party apps
    # 'safedelete',
    # 'debug_toolbar',
    
    'psycopg2',
    'wkhtmltopdf',
    'channels',
    # 'channels_postgres',


    # custom apps
    'apps.user',
    'apps.auth_user',
    # Master settings apps
    'apps.UoM',
    'apps.Categories',
    'apps.product_master',
    'apps.brands',
    'apps.accessories_master',
    'apps.accessories_kit',
    'apps.configuration_master',
    'apps.panels_and_others',
    'apps.addon_master',
    'apps.pricing_master',
    # Settings apps
    'apps.designations',
    # Customers apps
    'apps.customers',
    # Enquiries apps
    'apps.enquiries',
    # Estimations apps
    'apps.estimations',
    # signatures apps
    'apps.signatures',
    # projects apps
    'apps.projects',
    # suppliers apps
    'apps.suppliers',
    # enquiry types apps
    'apps.enquiry_type',
    # Industry types apps
    'apps.industry_type',
    # Surface Finish apps
    'apps.surface_finish',
    # Sealant_Types apps
    'apps.sealant_types',
    # Provisional apps
    'apps.provisions',
    # Quotations apps
    'apps.quotations_master',
    # Invoice Settings apps
    'apps.invoice_settings',
    # Company Settings apps
    'apps.companies',
    # Profiles Settings apps
    'apps.profiles',
    # Parts Settings apps
    'apps.product_parts',
    # Profile Type apps
    'apps.profile_types',
    # CoverCap and Pressure Plates
    'apps.cover_cap',
    # Tags
    # 'apps.tags',
    # Accociated Product apps
    'apps.associated_product',
    # Shopflowr apps
    'apps.shopfloors',
    # Workstations
    'apps.Workstations',
    # File_Manager
    'apps.file_manager',
    # Project Specification 
    'apps.project_specifications',
    'apps.vehicles_and_drivers',
    # Rating Head
    'apps.rating',
    # Others
    'apps.others',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    # 'whitenoise.middleware.WhiteNoiseMiddleware',
    
    # "debug_toolbar.middleware.DebugToolbarMiddleware",

]

ROOT_URLCONF = 'amoeba.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]



ASGI_APPLICATION = 'amoeba.asgi.application'
WSGI_APPLICATION = 'amoeba.wsgi.application'

# Database
DATABASES = DATABASES

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Qatar'

USE_I18N = True

USE_L10N = True
# USE_THOUSAND_SEPARATOR = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

# STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR, "static"),
# )



FIXTURE_DIRS = (
   os.path.join(BASE_DIR, 'static/', 'fixtures/'),
)

# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# MEDIA_URL = 'media/'


# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static/')]

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'user.User'

# email sending config
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'your-email'
EMAIL_HOST_PASSWORD = 'your-email account-password'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

# DB table prefix
TABLE_PREFIX = 'amoeba__'

# Project name for title
PROJECT_NAME = 'Amoeba'

QUOTATION_ID = 14200

EPS_ID = 1000

DN_ID = 1000

ENQ_ID = 14000
DATA_UPLOAD_MAX_NUMBER_FIELDS = 2000
TINYMC_API = 'qkri614joudyq5m9co5e0bbqza1c7oubtwozx1ir4xez3llu' # test
# TINYMC_API = 'vk4b85hr34evq23oo0dqn5a4q8u9hn889zefhr0jjx1mauyw' # Production
# TINYMC_API = ''
path_to_wkhtmltopdf = r'wkhtmltopdf.exe'
config = pdfkit.configuration(wkhtmltopdf=path_to_wkhtmltopdf)
