# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signatures', '0001_initial'),
        ('estimations', '0001_initial'),
        ('enquiries', '0002_initial'),
        ('project_specifications', '0001_initial'),
        ('addon_master', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_parts', '0002_initial'),
        ('quotations_master', '0001_initial'),
        ('configuration_master', '0003_initial'),
        ('rating', '0001_initial'),
        ('others', '0001_initial'),
        ('accessories_kit', '0003_initial'),
        ('provisions', '0001_initial'),
        ('customers', '0002_initial'),
        ('pricing_master', '0002_surface_finish_kit_surface_finish'),
        ('product_master', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('panels_and_others', '0001_initial'),
        ('brands', '0002_initial'),
        ('UoM', '0002_initial'),
        ('Categories', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_quotations',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_created_by_quotation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_quotations',
            name='estimations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_estimation_quotations', to='enquiries.temp_estimations'),
        ),
        migrations.AddField(
            model_name='temp_quotations',
            name='estimations_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_enquiry_versions_quotations', to='estimations.estimationversions'),
        ),
        migrations.AddField(
            model_name='temp_quotations',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_quotations',
            name='prepared_for',
            field=models.ManyToManyField(related_name='temp_quotation_prepared_customers', to='customers.Customers'),
        ),
        migrations.AddField(
            model_name='temp_quotations',
            name='quotation_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_quotation_customer', to='customers.customers'),
        ),
        migrations.AddField(
            model_name='temp_quotations',
            name='represented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_quotation_represent_customers', to='customers.contacts'),
        ),
        migrations.AddField(
            model_name='temp_quotations',
            name='signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='signatures.signatures'),
        ),
        migrations.AddField(
            model_name='temp_quotations',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temp_estimation_quotations_template', to='quotations_master.quotations_master'),
        ),
        migrations.AddField(
            model_name='temp_quotation_provisions',
            name='provision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temp_provision_type', to='provisions.provisions'),
        ),
        migrations.AddField(
            model_name='temp_quotation_provisions',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temp_estimation_quotation', to='estimations.temp_quotations'),
        ),
        migrations.AddField(
            model_name='temp_quotation_notes_comments',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_created_by_history_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_quotation_notes_comments',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_quotation_notes_comments',
            name='quotation_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_comments_quotation_notes', to='estimations.temp_quotation_notes'),
        ),
        migrations.AddField(
            model_name='temp_quotation_notes_comments',
            name='read_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_notes_comment_read_by_temp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_quotation_notes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_quotation_note_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_quotation_notes',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_quotation_notes',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_quotation_notes', to='estimations.temp_quotations'),
        ),
        migrations.AddField(
            model_name='temp_productcomments',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_product_comment_temp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_productcomments',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_productcomments',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimation_product_comment_temp', to='estimations.temp_estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='temp_pricingoption',
            name='estimation_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temp_estimate_main_pricingoption', to='estimations.temp_estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='temp_pricingoption',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_mainproductsilicon',
            name='estimation_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_product_silicon_temp', to='estimations.temp_estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='temp_mainproductsilicon',
            name='external_sealant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_product_external_sealant_temp', to='pricing_master.sealant_kit'),
        ),
        migrations.AddField(
            model_name='temp_mainproductsilicon',
            name='internal_sealant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_product_internal_sealant_temp', to='pricing_master.sealant_kit'),
        ),
        migrations.AddField(
            model_name='temp_mainproductsilicon',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_mainproductsilicon',
            name='mullion_gasket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_product_mullion_gasket_temp', to='pricing_master.sealant_kit'),
        ),
        migrations.AddField(
            model_name='temp_mainproductsilicon',
            name='polyamide_gasket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_product_polyamide_gasket_temp', to='pricing_master.sealant_kit'),
        ),
        migrations.AddField(
            model_name='temp_mainproductsilicon',
            name='transom_gasket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_product_transom_gasket_temp', to='pricing_master.sealant_kit'),
        ),
        migrations.AddField(
            model_name='temp_mainproductsecondtaryglass',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_product_temp_secondary_glass_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_mainproductsecondtaryglass',
            name='estimation_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_product_temp_secondary_glass', to='estimations.estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='temp_mainproductsecondtaryglass',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_mainproductsecondtaryglass',
            name='sec_glass_specif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_product_temp_secondary_glass_specifi', to='panels_and_others.panelmasterspecifications'),
        ),
        migrations.AddField(
            model_name='temp_mainproductglass',
            name='estimation_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_product_glass_temp', to='estimations.temp_estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='temp_mainproductglass',
            name='glass_specif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_product_glass_specifi_temp', to='panels_and_others.panelmasterspecifications'),
        ),
        migrations.AddField(
            model_name='temp_mainproductglass',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_mainproductaluminium',
            name='estimation_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_product_aluminium_temp', to='estimations.temp_estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='temp_mainproductaluminium',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_mainproductaluminium',
            name='product_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuration_master.configurationsmaster'),
        ),
        migrations.AddField(
            model_name='temp_mainproductaluminium',
            name='surface_finish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aluminium_surface_finish_temp', to='pricing_master.surface_finish_kit'),
        ),
        migrations.AddField(
            model_name='temp_mainproductaddoncost',
            name='addons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='addon_master.addons'),
        ),
        migrations.AddField(
            model_name='temp_mainproductaddoncost',
            name='estimation_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estimations.temp_estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='temp_mainproductaddoncost',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_mainproductaccessories',
            name='accessory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accessory_item_in_kit_temp', to='accessories_kit.accessorieskititem'),
        ),
        migrations.AddField(
            model_name='temp_mainproductaccessories',
            name='estimation_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_product_accessory_temp', to='estimations.temp_estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='temp_mainproductaccessories',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_estimationprojectspecifications',
            name='estimations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temp_estimation_project_scope', to='enquiries.temp_estimations'),
        ),
        migrations.AddField(
            model_name='temp_estimationprojectspecifications',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_estimationprojectspecifications',
            name='specification_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temp_project_scope_in_estimation', to='project_specifications.projectspecifications'),
        ),
        migrations.AddField(
            model_name='temp_estimationproductcomplaints',
            name='estimation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimation_product_complaints', to='enquiries.temp_estimations'),
        ),
        migrations.AddField(
            model_name='temp_estimationproductcomplaints',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_estimationproductcomplaints',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_specification', to='enquiries.temp_enquiryspecifications'),
        ),
        migrations.AddField(
            model_name='temp_estimationproduct_associated_data',
            name='associated_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_product_temp', to='estimations.temp_estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='temp_estimationproduct_associated_data',
            name='estimation_main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='estimations.temp_estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='temp_estimationmainproductmergedata',
            name='estimation_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temp_main_product_merge', to='estimations.temp_estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='temp_estimationmainproductmergedata',
            name='merge_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temp_merge_product', to='estimations.estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='temp_estimationmainproduct',
            name='accessories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_product_accessory_temp', to='accessories_kit.accessorieskit'),
        ),
        migrations.AddField(
            model_name='temp_estimationmainproduct',
            name='boq_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_product_boq_temp', to='suppliers.billofquantity'),
        ),
        migrations.AddField(
            model_name='temp_estimationmainproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_product_brand_temp', to='brands.categorybrands'),
        ),
        migrations.AddField(
            model_name='temp_estimationmainproduct',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estimations.temp_estimationbuildings'),
        ),
        migrations.AddField(
            model_name='temp_estimationmainproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product_category_temp', to='Categories.category'),
        ),
        migrations.AddField(
            model_name='temp_estimationmainproduct',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_estimation_temp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_estimationmainproduct',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_estimationmainproduct',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estimations.temp_estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='temp_estimationmainproduct',
            name='panel_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_product_panel_brand_temp', to='panels_and_others.panelmasterbrands'),
        ),
        migrations.AddField(
            model_name='temp_estimationmainproduct',
            name='panel_product',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_product_glass_product_temp', to='product_master.product'),
        ),
        migrations.AddField(
            model_name='temp_estimationmainproduct',
            name='panel_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_product_panel_series_temp', to='panels_and_others.panelmasterseries'),
        ),
        migrations.AddField(
            model_name='temp_estimationmainproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_product_product_temp', to='product_master.product'),
        ),
        migrations.AddField(
            model_name='temp_estimationmainproduct',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_product_series_temp', to='product_parts.profile_kit'),
        ),
        migrations.AddField(
            model_name='temp_estimationmainproduct',
            name='specification_Identifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_product_specification_identifier_temp', to='enquiries.temp_enquiryspecifications'),
        ),
        migrations.AddField(
            model_name='temp_estimationmainproduct',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_product_suppliers_temp', to='suppliers.suppliers'),
        ),
        migrations.AddField(
            model_name='temp_estimationmainproduct',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_product_uom_temp', to='UoM.uom'),
        ),
        migrations.AddField(
            model_name='temp_estimationbuildings',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_estimation_building_temp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_estimationbuildings',
            name='estimation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enquiries.temp_estimations'),
        ),
        migrations.AddField(
            model_name='temp_estimationbuildings',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_estimation_usertimes',
            name='estimation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_estimation_active_time', to='enquiries.temp_estimations'),
        ),
        migrations.AddField(
            model_name='temp_estimation_usertimes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_estimation_generalnotes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_estimation_general_notes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_estimation_generalnotes',
            name='estimations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temp_estimation_generalnote', to='enquiries.temp_estimations'),
        ),
        migrations.AddField(
            model_name='temp_estimation_generalnotes',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_deduction_items',
            name='estimation_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temp_main_product_deduction_items', to='estimations.temp_estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='temp_deduction_items',
            name='item_desc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temp_main_product_deduction_item', to='estimations.temp_mainproductglass'),
        ),
        migrations.AddField(
            model_name='temp_deduction_items',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temp_auditlogmodel',
            name='estimation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temp_audit_log_estimation', to='enquiries.temp_estimations'),
        ),
        migrations.AddField(
            model_name='temp_auditlogmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_audit_log_product', to='estimations.temp_estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='temp_auditlogmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temp_audit_log_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote_send_detail',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_quotation_send', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote_send_detail',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote_send_detail',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_send_quotation', to='estimations.quotations'),
        ),
        migrations.AddField(
            model_name='quotations',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_quotation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotations',
            name='estimations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimation_quotations', to='enquiries.estimations'),
        ),
        migrations.AddField(
            model_name='quotations',
            name='estimations_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiry_versions_quotations', to='estimations.estimationversions'),
        ),
        migrations.AddField(
            model_name='quotations',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotations',
            name='prepared_for',
            field=models.ManyToManyField(related_name='quotation_prepared_customers', to='customers.Customers'),
        ),
        migrations.AddField(
            model_name='quotations',
            name='quotation_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_customer', to='customers.customers'),
        ),
        migrations.AddField(
            model_name='quotations',
            name='represented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_represent_customers', to='customers.contacts'),
        ),
        migrations.AddField(
            model_name='quotations',
            name='signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='signatures.signatures'),
        ),
        migrations.AddField(
            model_name='quotations',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estimation_quotations_template', to='quotations_master.quotations_master'),
        ),
        migrations.AddField(
            model_name='quotationdownloadhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_download_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationdownloadhistory',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationdownloadhistory',
            name='quotation_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='customers.customers'),
        ),
        migrations.AddField(
            model_name='quotationdownloadhistory',
            name='quotation_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_download_history', to='estimations.quotations'),
        ),
        migrations.AddField(
            model_name='quotation_provisions',
            name='provision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provision_type', to='provisions.provisions'),
        ),
        migrations.AddField(
            model_name='quotation_provisions',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimation_quotation', to='estimations.quotations'),
        ),
        migrations.AddField(
            model_name='quotation_notes_comments',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_notes_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation_notes_comments',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation_notes_comments',
            name='quotation_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_quotation_notes', to='estimations.quotation_notes'),
        ),
        migrations.AddField(
            model_name='quotation_notes_comments',
            name='read_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_notes_comment_read_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation_notes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_note_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation_notes',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation_notes',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_notes', to='estimations.quotations'),
        ),
        migrations.AddField(
            model_name='productcomments',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_product_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcomments',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcomments',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimation_product_comment', to='estimations.estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='productcategoryremarks',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_remark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategoryremarks',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategoryremarks',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimation_product', to='estimations.estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='pricingoption',
            name='estimation_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estimate_main_pricingoption', to='estimations.estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='pricingoption',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mainproductsilicon',
            name='estimation_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_product_silicon', to='estimations.estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='mainproductsilicon',
            name='external_sealant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_product_external_sealant', to='pricing_master.sealant_kit'),
        ),
        migrations.AddField(
            model_name='mainproductsilicon',
            name='internal_sealant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_product_internal_sealant', to='pricing_master.sealant_kit'),
        ),
        migrations.AddField(
            model_name='mainproductsilicon',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mainproductsilicon',
            name='mullion_gasket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_product_mullion_gasket', to='pricing_master.sealant_kit'),
        ),
        migrations.AddField(
            model_name='mainproductsilicon',
            name='polyamide_gasket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_product_polyamide_gasket', to='pricing_master.sealant_kit'),
        ),
        migrations.AddField(
            model_name='mainproductsilicon',
            name='transom_gasket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_product_transom_gasket', to='pricing_master.sealant_kit'),
        ),
        migrations.AddField(
            model_name='mainproductglass',
            name='estimation_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_product_glass', to='estimations.estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='mainproductglass',
            name='glass_specif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_product_glass_specifi', to='panels_and_others.panelmasterspecifications'),
        ),
        migrations.AddField(
            model_name='mainproductglass',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mainproductaluminium',
            name='estimation_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_product_aluminium', to='estimations.estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='mainproductaluminium',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mainproductaluminium',
            name='product_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuration_master.configurationsmaster'),
        ),
        migrations.AddField(
            model_name='mainproductaluminium',
            name='surface_finish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aluminium_surface_finish', to='pricing_master.surface_finish_kit'),
        ),
        migrations.AddField(
            model_name='mainproductaddoncost',
            name='addons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='addon_master.addons'),
        ),
        migrations.AddField(
            model_name='mainproductaddoncost',
            name='estimation_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mainproduct_addons', to='estimations.estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='mainproductaddoncost',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mainproductaccessories',
            name='accessory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accessory_item_in_kit', to='accessories_kit.accessorieskititem'),
        ),
        migrations.AddField(
            model_name='mainproductaccessories',
            name='estimation_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_product_accessory', to='estimations.estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='mainproductaccessories',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimationversions',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_enquiry_revision', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimationversions',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimationversions',
            name='main_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_version', to='estimations.estimationmaniversion'),
        ),
        migrations.AddField(
            model_name='estimationsubmitting_hours',
            name='estimation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimation_in_submiting', to='enquiries.estimations'),
        ),
        migrations.AddField(
            model_name='estimationsubmitting_hours',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimationsubmitting_hours',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimation_submitting_parameters', to='others.submittingparameters'),
        ),
        migrations.AddField(
            model_name='estimationprojectspecifications',
            name='estimations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimation_project_scope', to='enquiries.estimations'),
        ),
        migrations.AddField(
            model_name='estimationprojectspecifications',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimationprojectspecifications',
            name='specification_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_scope_in_estimation', to='project_specifications.projectspecifications'),
        ),
        migrations.AddField(
            model_name='estimationproductcomplaints',
            name='estimation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimation_product_complaints', to='enquiries.estimations'),
        ),
        migrations.AddField(
            model_name='estimationproductcomplaints',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimationproductcomplaints',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_specification', to='enquiries.enquiryspecifications'),
        ),
        migrations.AddField(
            model_name='estimationproduct_associated_data',
            name='associated_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_product', to='estimations.estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='estimationproduct_associated_data',
            name='estimation_main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='estimations.estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='estimationmaniversion',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimationmainproductmergedata',
            name='estimation_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_product_merge', to='estimations.estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='estimationmainproductmergedata',
            name='merge_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merge_product', to='estimations.estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='estimationmainproduct',
            name='accessories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_product_accessory', to='accessories_kit.accessorieskit'),
        ),
        migrations.AddField(
            model_name='estimationmainproduct',
            name='boq_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_product_boq', to='suppliers.billofquantity'),
        ),
        migrations.AddField(
            model_name='estimationmainproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_product_brand', to='brands.categorybrands'),
        ),
        migrations.AddField(
            model_name='estimationmainproduct',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_product_building', to='estimations.estimationbuildings'),
        ),
        migrations.AddField(
            model_name='estimationmainproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product_category', to='Categories.category'),
        ),
        migrations.AddField(
            model_name='estimationmainproduct',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_estimation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimationmainproduct',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimationmainproduct',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estimations.estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='estimationmainproduct',
            name='panel_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_product_panel_brand', to='panels_and_others.panelmasterbrands'),
        ),
        migrations.AddField(
            model_name='estimationmainproduct',
            name='panel_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_product_glass_product', to='product_master.product'),
        ),
        migrations.AddField(
            model_name='estimationmainproduct',
            name='panel_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_product_panel_series', to='panels_and_others.panelmasterseries'),
        ),
        migrations.AddField(
            model_name='estimationmainproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_product_product', to='product_master.product'),
        ),
        migrations.AddField(
            model_name='estimationmainproduct',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_product_series', to='product_parts.profile_kit'),
        ),
        migrations.AddField(
            model_name='estimationmainproduct',
            name='specification_Identifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_product_specification_identifier', to='enquiries.enquiryspecifications'),
        ),
        migrations.AddField(
            model_name='estimationmainproduct',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_product_suppliers', to='suppliers.suppliers'),
        ),
        migrations.AddField(
            model_name='estimationmainproduct',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_product_uom', to='UoM.uom'),
        ),
        migrations.AddField(
            model_name='estimationbuildings',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_estimation_building', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimationbuildings',
            name='estimation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimation_building', to='enquiries.estimations'),
        ),
        migrations.AddField(
            model_name='estimationbuildings',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimation_usertimes',
            name='estimation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimation_active_time', to='enquiries.estimations'),
        ),
        migrations.AddField(
            model_name='estimation_usertimes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimation_rating',
            name='estimations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimation_rating', to='enquiries.estimations'),
        ),
        migrations.AddField(
            model_name='estimation_rating',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimation_rating',
            name='rating_parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimation_rating_parameter', to='rating.ratinghead'),
        ),
        migrations.AddField(
            model_name='estimation_generalnotes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimation_general_notes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimation_generalnotes',
            name='estimations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimation_generalnote', to='enquiries.estimations'),
        ),
        migrations.AddField(
            model_name='estimation_generalnotes',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deduction_items',
            name='estimation_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_product_deduction_items', to='estimations.estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='deduction_items',
            name='item_desc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_product_deduction_item', to='estimations.mainproductglass'),
        ),
        migrations.AddField(
            model_name='deduction_items',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlogmodel',
            name='estimation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_log_estimation', to='enquiries.estimations'),
        ),
        migrations.AddField(
            model_name='auditlogmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log_product', to='estimations.estimationmainproduct'),
        ),
        migrations.AddField(
            model_name='auditlogmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_log_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
