# Generated by Django 3.2.4 on 2025-04-20 07:27

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanelMasterBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'amoeba__PanelMasterBase',
            },
        ),
        migrations.CreateModel(
            name='PanelMasterBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'amoeba__PanelMasterBrands',
            },
        ),
        migrations.CreateModel(
            name='PanelMasterConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive')], null=True)),
                ('date', models.DateTimeField()),
                ('price_per_sqm', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('min_price_and_area_req', models.BooleanField(blank=True, default=False, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('min_area', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=9, null=True)),
                ('markup_percentage_req', models.BooleanField(blank=True, default=False, null=True)),
                ('markup_percentage', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('u_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('shading_coefficient', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('panel_quoted_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'amoeba__PanelMasterConfiguration',
            },
        ),
        migrations.CreateModel(
            name='PanelMasterSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('series', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'amoeba__PanelMasterSeries',
            },
        ),
        migrations.CreateModel(
            name='PanelMasterSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('specifications', models.CharField(blank=True, max_length=500, null=True)),
                ('glass_type', models.IntegerField(blank=True, choices=[(1, 'Double Glass Unit'), (2, 'Single Glass')], default=0, null=True)),
                ('outer', models.CharField(blank=True, max_length=500, null=True)),
                ('air_space', models.CharField(blank=True, max_length=500, null=True)),
                ('inner', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'amoeba__PanelMasterSpecifications',
            },
        ),
    ]
