# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panels_and_others', '0001_initial'),
        ('Categories', '0002_initial'),
        ('brands', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='panelmasterspecifications',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_panel_specifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='panelmasterspecifications',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='panelmasterspecifications',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='panel_series', to='panels_and_others.panelmasterseries'),
        ),
        migrations.AddField(
            model_name='panelmasterseries',
            name='brands',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='panel_brand', to='panels_and_others.panelmasterbrands'),
        ),
        migrations.AddField(
            model_name='panelmasterseries',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_panel_series', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='panelmasterseries',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='panelmasterconfiguration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_panel_config', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='panelmasterconfiguration',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='panelmasterconfiguration',
            name='panel_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='panel_master_specification', to='panels_and_others.panelmasterspecifications'),
        ),
        migrations.AddField(
            model_name='panelmasterbrands',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_panel_brands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='panelmasterbrands',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='panelmasterbrands',
            name='panel_brands',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brands.categorybrands'),
        ),
        migrations.AddField(
            model_name='panelmasterbrands',
            name='panel_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='panel_category', to='Categories.category'),
        ),
        migrations.AddField(
            model_name='panelmasterbase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_panel_base', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='panelmasterbase',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='panelmasterbase',
            name='panel_category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Categories.category'),
        ),
    ]
