# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoverCap_PressurePlates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('cap_name', models.CharField(max_length=225)),
                ('cap_code', models.CharField(max_length=50)),
                ('cap_thickness', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cap_weight_lm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cap_formula', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'amoeba__CoverCap_and_PressurePlates',
            },
        ),
    ]
