# Generated by Django 3.2.4 on 2025-04-20 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('accessory_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, upload_to='accessories/image')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Published'), (2, 'Draft'), (3, 'Scheduled'), (4, 'Inactive')], null=True)),
            ],
            options={
                'db_table': 'amoeba__Accessories',
            },
        ),
    ]
